MECHANISM_BASE_TERMS: list[str] = [
    "mimetic",
    "co[- ]?factor",
    "(?:cross[ -]?)?linker",
    "introducer",
    "metabolite",
    "anti[ -]?metabolite",
    "surfactant",
    "donor",
    "vaccine",
    "vaccine adjuvant",
    "activity",
    "effect",
    "introducer",
    "dilator",
    "disinfectant",
    "analgesic",
    "anaesthetic",
    "agent",
    "emitter",
    "lubricant",
    "phototherapy",
    "diuretic",
    "anti[ -]?microbial",
    "anti[ -]?biotic" "anti[ -]?infective",
    "anti[ -]?inflammatory",
    "anti[ -]?bacterial",
    "anti[ -]?viral",
    "emollient",
    "contraception",
    "oligo[ ]?nucleotide",
    "growth factor",
    "factor",
    "interference",
    "toxin",
    "differentiation",
    "adjuvant",
    "precursor",
    "pro[ -]?drug",
    "pathway",
]
BIOLOGIC_BASE_TERMS: list[str] = [
    "antigen",
    "neoantigen",
    "antibodie",
    "antibody",
    "antibody molecule",
    "autoantibody",
    "autoantibodie",
    "isoform",
    "enzyme",
    "nuclease",
    "anion",
    "ion",
    "exosome",
    "rna",
    "micro[ ]?rna",
    "messenger rna",
    "mrna",
    "sh[ ]?rna",
    "hairpin rna",
    "si[ ]?rna",
    "ds[ ]?rna",
    "double[- ]?stranded rna",
    "scfv",  # single-chain variable fragment
    "liposome",
    "vector",
    "cell",
    "stem cell",
    "gene therap(?:y|ie)",
    "immunotherap(?:y|ie)",
    "chemotherap(?:y|ie)",  # not necessary biologic, more class/descriptive
    "decomposition",
    "clone",
]
COMPOUND_BASE_TERMS: list[str] = [
    "reagent",
    "derivative",
    "composition",
    "compound",
    "formulation",
    "stereoisomer",
    "analog",
    "analogue",
    "homologue",
    "drug",
    "therapy",
    "therapie",
    "regimen",
    "particle",
    "nanoparticle",
    "microparticle",
]

INTERVENTION_BASE_TERMS = [
    *BIOLOGIC_BASE_TERMS,
    *MECHANISM_BASE_TERMS,
    *COMPOUND_BASE_TERMS,
]

MECHANISM_BASE_TERM_SETS: list[list[str]] = [
    [
        "immunization",
        "immunizing",
        "immunize",
        "immunization",
        "immunological",
        "immunoconjugate",
        "immunotherapy",
    ],
    ["regenerate", "regeneration", "regenerating", "regeneration"],
    ["stabilizer", "stabilizing", "stabilize", "stabilization"],
    [
        "(?:neuro)?modulator",
        "(?:neuro)?modulating",
        "(?:neuro)?modulation",
        "(?:neuro)?modulate",
    ],
    ["modifier", "modifying", "modification"],
    ["inhibitor", "inhibition", "inhibiting", "inhibit"],
    ["agonist", "agonizing", "agonize", "agonism"],
    ["antagonist", "antagonizing", "antagonize", "antagonism"],
    [
        "activator",
        "activation",
        "activating",
    ],
    [
        "(?:de)?sensitizer",
        "(?:de)?sensitization",
        "(?:de)?sensitizing",
        "(?:de)?sensitize",
    ],
    ["suppressor", "suppression", "suppressing", "suppress"],
    ["stimulator", "stimulation", "stimulating", "stimulate"],
    ["modulate", "modulates? binding", "modulating", "modulation", "modulator"],
    ["promotion", "promoting", "promote"],
    ["enhancement", "enhancing", "enhance", "enhancer"],
    ["regulator", "regulation", "regulating"],
    ["degrader", "degradation", "degrading", "degrade"],
    ["inducer", "inducing", "induce", "induction"],
    ["promoter", "promoting", "promote", "promotion"],
    ["blocker", "blockade", "blocking", "block"],
]

BIOLOGIC_BASE_TERM_SETS: list[list[str]] = [
    ["protein", "proteins? binding"],
    ["(?:poly)peptide", "(?:poly)peptides? binding"],
    ["(?:poly)?nucleotide", "(?:poly)?nucleotides? binding"],
    ["ligand", "ligands? binding", "ligands? that bind"],
    ["fragment", "fragments? binding", "fragments? that bind"],
]
COMPOUND_BASE_TERM_SETS: list[list[str]] = [
    ["conjugation", "conjugating", "conjugate"],
    ["molecule", "molecules? binding"],
]

INTERVENTION_BASE_TERM_SETS: list[list[str]] = [
    *MECHANISM_BASE_TERM_SETS,
    *BIOLOGIC_BASE_TERM_SETS,
    *COMPOUND_BASE_TERM_SETS,
]

INTERVENTION_BASE_PREFIXES = [
    "anti",
    "chimeric",
    "cyclic",
    "reversible",
    "irreversible",
    "new",
    "bi-?specific",
    "monoclonal",
    "acceptable",
    "receptor",
    "(?:ion )?channel",
    "encoding",
    "encoders?",
    "positive",
    "negative",
    "allosteric",
    "small molecule",
    "potent",
    "inventive",
    "selective",
    "novel",
    "heterocyclic",
    "partial",
    "inverse",
    "dual",
    "single",
    "short",
    "recombinant",
]
