from constants.patterns.device import DEVICE_RES
from constants.patterns.intervention import (
    COMPOUND_BASE_TERMS_GENERIC,
    INTERVENTION_PREFIXES_GENERIC,
)

from .types import WordPlace

REMOVAL_WORDS_PRE: dict[str, WordPlace] = {
    **{k: "leading" for k in INTERVENTION_PREFIXES_GENERIC},
    "such": "all",
    "method": "all",
    "obtainable": "all",
    "different": "all",
    "-+": "leading",
    "stable": "all",
    "various": "all",
    "the": "leading",
    "example": "all",
    "unwanted": "leading",
    "comprised?": "all",
    "contagious": "leading",
    "recognition": "trailing",
    "binding": "trailing",
    "prevention": "leading",
    "that": "trailing",
    "discreet": "all",
    "properties": "trailing",
    "administration(?: of)?": "all",
    "treatment(?: of)?": "all",
    "derived": "all",
    "library": "all",
    "more": "leading",
    "technique": "trailing",
    "classic": "all",
    "present": "leading",
    "invention": "all",
    "various": "leading",
    "construct": "trailing",
    "particular": "all",
    "uses(?: thereof| of)": "all",
    "designer": "all",
    "obvious": "leading",
    "thereof": "all",
    "specific": "all",
    "in": "leading",
    "more": "leading",
    "a": "leading",
    "non[ -]?toxic": "leading",
    "(?:non )?selective": "leading",
    "adequate": "leading",
    "improv(?:ed|ing)": "all",
    r"\b[(]?e[.]?g[.]?,?": "all",
    "-targeted": "all",
    "long[ -]?acting": "leading",
    "other": "leading",
    "more": "leading",
    "of": "trailing",
    "symptom": "trailing",
    "condition": "trailing",
    "be": "trailing",
    "use": "trailing",
    "efficacy": "all",
    "pharmaceutical compositions?(?: comprising)?": "all",
    "therapeutic procedure": "all",
    "therefor": "all",
    "(?:co[ -]?)?therapy": "trailing",
    "(?:pharmaceutical |chemical )?composition": "trailing",
    "(?:pre[ -]?)?treatment (?:method|with|of)": "all",
    "treating": "all",
    "contact": "trailing",
    "portion": "trailing",
    "intermediate": "all",
    "suitable": "all",
    "and uses thereof": "all",
    "procedure": "all",  # TODO
    "relevant": "all",
    "patient": "all",
    "thereto": "all",
    "against": "trailing",
    "other": "leading",
    "use of": "leading",
    "certain": "all",
    "working": "leading",
    "on": "trailing",
    "in(?: a)?": "trailing",
    "(?: ,)?and": "trailing",
    "and ": "leading",
    "the": "trailing",
    "with": "trailing",
    "of": "trailing",
    "for": "trailing",
    "=": "trailing",
    "unit(?:[(]s[)])?": "trailing",
    "measur(?:ement|ing)": "all",
    # "system": "trailing", # CNS?
    "[.]": "trailing",
    "analysis": "all",
    "management": "all",
    "accelerated": "all",
    "below": "trailing",
    "diagnosis": "all",
    "fixed": "leading",
    "pharmacological": "all",
    "acquisition": "all",
    "production": "all",
    "level": "trailing",
    "processing(?: of)?": "all",
    "lead candidate": "all",
    "control": "trailing",
    "variant": "trailing",
    "variet(?:y|ie)": "trailing",
    "famil(?:y|ie)": "trailing",
    "(?:pharmaceutically|physiologically) (?:acceptable |active )?": "leading",
    "based": "trailing",
    "an?": "leading",
    "active": "all",
    "wherein": "all",
    "additional": "all",
    "additive": "all",
    "advantageous": "all",
    "aforementioned": "all",
    "aforesaid": "all",
    "efficient": "all",
    "first": "all",
    "second": "all",
    "(?:ab)?normal": "all",
    "inappropriate": "all",
    "compounds as": "all",
    "formula [(][ivxab]{1,3}[)]": "trailing",
    "is": "leading",
    "engineered": "leading",
    "engineered": "trailing",
    "medicament": "all",
    "medicinal": "all",
    "sufficient": "all",
    "due": "trailing",
    "locate": "all",
    "specification": "all",
    "detect": "all",
    "similar": "all",
    "contemplated": "all",
    "predictable": "all",
    "dos(?:e|ing|age)": "leading",
    "conventional": "leading",
    "contemplated": "all",
    "is indicative of": "all",
    "via": "leading",
    "effect": "trailing",
    "level": "trailing",
    "disclosed": "all",
    "wild type": "all",  # TODO
    "(?:high|low)[ -]?dos(?:e|ing|age)": "all",
    "effects of": "all",
    "soluble": "leading",
    "competitive": "leading",
    "activatable": "all",
    # "type": "leading", # type II diabetes
    # model/source
    "murine": "all",
    "monkey": "all",
    "non[ -]?human": "all",
    "primate": "all",
    "mouse": "all",
    "mice": "all",
    "human": "all",  # ??
    "rat": "all",
    "rodent": "all",
    "rabbit": "all",
    "porcine": "all",
    "bovine": "all",
    "equine": "all",
    "mammal(?:ian)?": "all",
}

REMOVAL_WORDS_POST: dict[str, WordPlace] = {
    **dict(
        [
            (t, "conditional_trailing")
            for t in [
                *COMPOUND_BASE_TERMS_GENERIC,
                "activity",
                "agent",
                "effect",
                "pro[ -]?drug",
            ]
        ]
    ),
    **REMOVAL_WORDS_PRE,
}

DELETION_TERMS = [
    *DEVICE_RES,
    "[(][0-9a-z]{1,4}[)]?[.,]?[ ]?",
    "[0-9., ]+",  # del if only numbers . and ,
    # mangled
    "non-overlapping double-stranded regions separated",  # ??
    "(?:.* )? capable",  # material capable, etc
    "salt as an",
    "further",
    "individual suffering",
    ".{1,5}-",  # tri-
    "(?:composition|compound|substance|agent|kit|group)s? (?:useful|capable)",
    "optionally other modification",
    "co[- ]?operate",
    "light[ -]?receiving",
    "resultant",
    "optionally other",
    "above[ -]?mentioned",
    ".* of",
    ".* comprising",
    ".* tubular",
    "composition (?:contain|compris)",
    "[a-zA-Z0-9]+-containing",
    "by-",
    "cur",
    "co-",
    "therefrom",
    "said .*",
    "quantify",
    "citrat",
    "functional",
    "cross[ -]?linking",
    "biocompatibility",
    "particle diamet",
    "embodiment",
    "quantificat",
    "(?:.* )?rate",
    "correspond",
    "water[- ]?soluble",
    "illustrat",
    "cross[- ]?link",
    "antigen-binding",
    "sterilization",
    "regeneration",
    "particulat",
    "embodiment",
    "least partial",
    "reform",
    "conformat",
    # thing (unwanted because generic)
    "receptor",
    "product .*",
    "pathogen(?:ic)?",
    "regenerative medicine",
    "basic amino acid",
    "(?:.* )?characteristic",
    "response",
    "single piece",
    "product gas",
    r"agent\(s\)",
    "medical purpose",
    "cell membrane",
    "(?:.* )?part",
    "(?:product|reaction) mixture",  # single dose
    "(?:.* )?activit",
    "(?:.* )?member",
    "module",
    "group",
    "product stream",
    "operator",
    "field of .*",
    # thing (unwanted because wrong type of thing)
    "(?:.* )?propert(?:y|ie)",
    "constraint",
    "(?:side|adverse)[ -]?effect",
    "leaflet",
    "passageway",
    "ability",
    "determinat",  # determination
    "anatomical structure",
    "distract",  # distraction
    "(?:.* )?configuration",
    "considerat",  # consideration
    "strateg(?:y|ie)",
    "(?:.* )?arrangement",
    "(?:.* )?position",
    "(?:.* )?frame",
    "(?:.* )?feature",
    "heat generat",
    "(?:.* )?industry",
    "impact modifier",
    "scratch resistance",
    "gene transfer",
    "mother milk",
    "drug development",
    ".*administration",
    ".*patient",
    "(?:.* )?pest",
    "(?:.* )?examinee",
    "(?:.* )?staff",
    "(?:.* )?trial",
    "(?:.* )?infant",
    "(?:.* )?prospect",
    "(?:.* )?room",
    "professional",
    "(?:.* )?person(?:nel)?",
    "guest",
    "body part",
    "(?:.* )?patent",
    "(?:.* )?pathway",
    "(?:.* )?animal",
    "(?:.* )?retardant",  # e.g. flame retardant
    "aroma",
    "(?:.* )?reaction",
    "(?:.* )?cosmetic",
    "(?:.* )?fragrance",
    "silica",
    "perfum",
    "bacteri(?:um|a)",
    "(?:.*)?station",
    "(?:.* )?location",
    "(?:.* )?mode",
    "(?:.* )?region",
    "(?:tumou?r|eukaryotic|live|normal|animal|bacterial|yeast|single|skin|cancer(?:ous)?|insect|host|biological|isolated|primary|diseased?) cell",
    "virus",  # generic
    "titanium dioxide",
    "microorganism",
    "(?:.* )?area",
    "(?:.* )?power",
    "(?:.* )?site",
    "(?:.* )?signal",
    "(?:.* )?layer",
    "(?:.* )?surface",  # device?
    # effect
    "deactivat",
    "friction",
    "compressive force",
    "correcting dysfunction",
    # "bleaching",
    "vibrat",
    "moisturi[zs]",
    "induc(?:es?d?|ing) differentiation",
    "cool",
    "connect",
    "deterioration",
    "detrimental",
    "(?:.* )?absorb",
    "(?:.* )?disengage",
    "adjustment",
    "lubricat",
    "chain transfer",
    "(?:.* )?abrasive",
    "(?:.* )?retardancy",  # e.g. flame retardant
    "film[ -]?form",
    "heat transfer",
    # "nucleating",
    "cell death",
    "deformable",
    "(?:.* )?growth",  # TODO: disease?
    "(?:.* )?resistance",
    "(?:.* )?addition",
    "ameliorat",
    "transformant",
    "deformation",
    "reduction",
    "fixation",
    "stiffen",
    "suction",
    # disease
    "disease state",
    "dysfunction",
    "related (?:disorder|condition|disease)",
    "(?:disorder|condition|disease)s related",
    "disease",
    "syndrome",
    "disorder",
    "dysfunction",
    # part or characteristic of body, or fluid
    "(?:.* )?urine",
    "(?:.* )?appendage",
    "(?:.* )?ventricle",
    "(?:.* )?aorta",
    "(?:.* )?intervertebral disc",
    "(?:.* )?mucosa",
    "(?:.* )?retina",
    "(?:.* )?artery",
    "(?:.* )?vein",
    "(?:.* )?tissue",
    "(?:.* )?septum",
    "(?:.* )?vasculature",
    "(?:.* )?tendon",
    "(?:.* )?ligament",
    "bone fragment",
    "vertebral",
    "(?:.* )?obturator",
    "(?:.* )?atrium",
    "tibial?",
    "transdermal",
    "(?:.* )?femur",
    "(?:.* )?core",  # device
    "(?:.* )?vesicle",
    "(?:.* )?valve",  # device
    "(?:.* )?atrium",
    "(?:.* )?nail",  # device
    "(?:.* )?joint",
    "(?:.* )?cavity",
    "skin",
    "hair",
    "vascular",
    "capillary",
    "bodily",
    "cornea",
    "vertebra",
    "spine",
    "eye",
    "urea",
    "blood",
    "gastric",
    "gastrointestinal(?: tract)?",
    "cartilage",
    "jaw",
    "liver",
    "heart",
    "intraocular len",
    "femoral",
    "respiratory(?: tract)?",
    "pulmonary",
    "uterus",
    "lung",
    "plasma",
    "spinal column",
    "muscle",
    "kidney",
    "prostate",
    "pancreas",
    "ocular",
    "spleen",
    "gallbladder",
    "bladder",
    "ureter",
    "urethra",
    "esophagus",
    "stomach",
    "intestin(?:e|al)",
    "colon",
    "rectum",
    "trachea",
    "bronch(?:ial|us)",
    "larynx",
    "pharynx",
    "nasal",
    "sinus",
    "arterial",
    "venous",
    "lymph(?:atic)?(?: node| vessel)?",
    # category errors
    "(?:.*)?dimensional",
    "pathological",
    "consideration",
    "combin",
    "functionaliz",
    "plurality",
    "physical",
    "demonstrat",
    "engaged position",
    "cell[- ]?free",
    "contribut",
    "advantage",
    "(?:.* )?side",  # base end side
    "accept",
    "solid state",
    "susceptible",
    "(?:.* )?typ",  # type
    "processability",
    "auxiliary",
    "present tricyclic",
    "wherein(?: a)?",
    "particle size",
    "fragment of",
    "concentric(?:al)?",
    "(?:.* )?coupled",
    "(?:.* )?axis",
    "(?:.* )?path",
    "(?:.* )?pattern",
    "(?:.* )?plan",
    "(?:.* )?stage",  # ??
    "(?:.* )?quantit",
    "functional group",
    "drug discovery",
    "combinatorial",
    "compound having",
    "non-",
    # generic
    "multi[- ]?component",
    "discret",  # discrete
    "problem",
    "further",
    "parent",
    "structure(?: directing)?",
    "technology",
    "branch",
    "(?:leading )?edge",
    "approach",
    "extension",
    "space",
    "point",
    "mount",
    "wall",
    "cell(?: cycle| wall| line)",
    "channel",  # todo?
    "design",
    "general structural",
    "piece",
    "attribute",
    "preform",
    "DNA sequence",
    "(?:medical|treatment|operation) (?:fluid|zone|container|section|technology)",
    "object",
    "(?:drug )?target",
    "biologically active",
    "(?:.* )?sample",
    "therapeutically",
    "pharmaceutically-",
    "physiological",
    "pharmaceutically[- ]accept",
    "therapy",
    "(?:general |chemical )?formula(?: i{1,3}){0,3}(?: [0-9a-z]){0,3}",
    "components?(?: i{1,3})?(?: [0-9a-z])?",
    "compounds?(?: i{1,3})?(?: [0-9a-z])?",
    "(?:medicinal|bioactive|biological)(?: activity)?",
    "(?:pharmaceutical|pharmacological|medicinal) composition(?: containing| comprising)?",
    "medicine compound",
    "wherein said compound",
    "pharmaceutical",
    "pharmacological",
    "(?:.* )?compounds? of(?: formula)?",
    "compound of",
    "(?:pharmacologically|pharmaceutically|biologically) active agent",
    "(?:bioactive |medicinal )?agent",
    "chemical entit",
    # general characteristic
    "utility",
    "detachabl",
    "proximal",
    "hydrogenat",  # hydrogenated
    "chiral",
    "embolic",
    "traction",
    "annular",
    "molten",
    "(?:solid )?phase",
    "disinfect",  # disinfectant is fine, but not disinfecting
    "(?:open |closed )?configuration",
    "dispersib(?:le|ilit)",
    "photodynamic",
    "structural",
    "accurate",
    "bioavailabilit",
    "usefulness",
    "(?:.* )?conductivit",
    "multi[ -]?function",
    "elastic(?:ity)?",
    "symmetric(?:al)?",
    "biocompatible",
    "biocompatibilt",
    "bioactivit",
    "medicinal",
    "cellular",
    "natural",
    "substantially free",
    "therapeutically active",
    # characteristics / descriptors
    "helical",
    "ingestibl",
    "humaniz",  # humanized
    "sheet-like",
    "hydrophobicity",
    "(?:high |low )?concentration",
    "(?:.* )?acceptable",  # e.g. agrochemically acceptable
    "solubilit",
    "(?:.* )?refractive index",
    "uniform(?:it)?",
    "(?:non[ -]?)?conductive",
    "granular",
    "luminescent",
    "(?:.* )?bound",
    "amorphous",
    "purif",  # purified
    "hardness",
    "deactivate",  # ??
    "(?:.* )?stability",
    "planar",
    "fatty",
    "compressible",
    "(?:.* )?bond",
    "(?:.* )?perpendicular",
    "(?:.* )?specificity",
    "(?:.* )?domain",
    "storage stability",
    "conductive",
    "flexible",
    "dermatological",
    "bifunctional",
    "in vitro",
    "fibrous",
    "biodegrad",
    "resilient",
    "fluorescent",
    "superabsorbent",
    "non[- ]?woven(.*)?",
    "crystalline",
    "volatile",
    "phenolic",
    "edibl",
    "(?:non[ -]?|potentially )?therapeutic",
    "water[ -]?insoluble",
    "unsaturat",
    "adhes",
    "porous",
    "dispens",
    "impedanc",
    "radioact",
    # "cleans?(?:ing|er|ed)",
    "optionally substitut",
    "non[ -]?invasive",
    "reinforc",
    "(?:.* )?chain",
    "aqueous",
    "(?:.* )?bond",
    "concentration",
    "(?:.* )?conductive",
    "(?:.* )?recombinant",
    "(?:.* )?genetic",
    "(?:.* )?acidic",
    "(?:.* )?unsubstituted",
    "(?:.* )?gaseous",
    "(?:.* )?aromatic",
    "(?:.* )?conjugated",
    "(?:.* )?polymeric",
    "(?:.* )?polymerizable",
    "(?:.* )?oligomeric",
    "(?:.* )?synergistic",
    "(?:.* )?immunogenic",
    "(?:.* )?amphiphilic",
    "(?:.* )?macrocyclic",
    "(?:.* )?elastic",
    "(?:.* )?catalytic",
    "(?:.* )?hydrophilic",
    "(?:.* )?ophthalmic",
    "(?:.* )?heterocyclic",
    "(?:.* )?hydrophobic",
    "(?:.* )?enzymatic",
    "(?:.* )?lipophilic",
    "(?:.* )?biodegradabilit",
    "(?:.* )?affinity",
    "(?:.* )?residual",
    "(?:.* )?rigid",
    "(?:.* )?cyclic",
    "(?:.* )?adverse",
    # physical process
    "elut",  # elution
    "drug release",
    "sustained[ -]?release",
    "disintegrat",
    "evaporat",
    "agglomerat",
    # measurable thing
    "(?:.* )?curvature",
    "(?:.* )?degree",
    "spatial resolution",
    "oxygen concentrat",
    "(?:.* )?number",
    "(?:.* )?cost",
    "(?:.* )?distance",
    "(?:.* )?frequency",  # also procedure or device
    "(?:.* )?torque",
    "(?:.* )?divergence",
    "(?:.* )?weight",
    "(?:.* )?wavelength(?: .*)?",
    "(?:.* )?charge",
    "(?:.* )?band",
    "(?:.* )?viscosity",
    "(?:.* )?volume",
    "(?:.* )?distribution",
    "(?:.* )?amount",
    "refractive index",
    "phase change",
    "(?:.* )?pressure",
    "(?:.* )?strength",
    "(?:.* )?population",
    "(?:.* )?end",
    "(?:.*[ -])?temperatures?(?: range|high(?:er)?)?",
    "(?:.* )?ratio",
    "(?:.* )?deliver",
    "(?:.* )?step",
    "(?:.* )?value",
    "(?:.* )?time",
    # roa
    "aerosol",
    "parenteral",
    "inhalation",
    "insufflation",
    "intranasal",
    "intramuscular",
    "intravenous",
    "subcutaneous",
    "topical",
    # intangible thing
    "(?:.* )?concept",
    "(?:.* )?data",
    "(?:.* )?integer",
    "(?:.* )?language",
    "(?:.* )?information",
    "(?:.* )?report",
    "(?:.* )?parameter",
    "(?:.* )?constant",
    "(?:.* )?longitudinal",
    "(?:.* )?equivalent",
    "(?:.* )?subset",
    "time period",
    "(?:.* )?memory",
    # material
    "(?:.* )?metal",
    # non-medical procedure or process"
    "session",
    "wash",
    "solid-liquid separation",
    "mix",
    # "pattern form",  # pattern forming
    "crystallizat",
    "quantitat",
    "(?:administrative )?procedure",
    "support (?:.*)",  # ??
    "(?:.* )?communicat",
    "(?:.* )?sequenc",
    # "thermoset",  # thermosetting
    "(?:.* )?(?:micro)?process",
    # procedure
    "punctur",  # puncture
    "transplant(?:at)",  # transplantation
    "(?:.* )?electrolysis",
    "(?:.* )?incision",
    "(?:.* )?graft",
    "(?:.* )?ablation",
    "(?:.* )?technique",
    "(?:.* )?retract",
    "(?:.* )?care",
    "(?:.* )?amplification",
    "(?:.* )?ablation",
    "(?:.* )?surger(?:y|ie)",
    "(?:.* )?operat",
    "(?:.* )?extraction",
    "brachytherapy",
    "radiotherapy",
    "sealant",
    "microelectronic",
    # agtech
    "pest control",
    "(?:.* )?feedstock",
    "(?:.* )?biomass",
    "(?:.* )?agrochemical",
    "(?:.* )?herbicid(?:e|al)(?: activity)?",
    "(?:.* )?insecticid(?:e|al)(?: activity)?",
    "(?:.* )?biocid(?:e|al)(?: activity)?",
    "(?:.* )?fungicid(?:e|al)(?: activity)?",
    "(?:.* )?pesticid(?:e|al)(?: activity)?",
    "(?:.* )?plant",
    "drought tolerance",
    "biofuel",
    "biodiesel",
    "plant growth regulator",
    # end agtech
    # start industrial
    "corros",  # corrosion
    "asphalt",
    "heat exchang",
    "carbon black",
    "(?:.* )?composite",
    "(?:.* )?manufactur",
    "(?:.* )?graphite",
    "(?:.* )?metal",  # temporary?
    "palladium",
    "cobalt",
    "propane",
    "(?:.* )?energy",
    "electric(?:al) .*",
    "formaldehyde",  # ??
    "aromatic ring",  # industrial
    "polymer matrix",  # industrial
    "polyolefin",  # industrial
    "polyisocyanate",  # industrial
    "alkaline",  # industrial
    "trifluoromethyl",  # industrial
    "thermoplastic(?: .*)?",  # industrial
    "(?:.* )?resin",
    "(?:.* )?epoxy",
    "(?:.* )?polyurethane",
    "ethylene",
    "alkylat",
    "carbonyl",
    "aldehyde",
    # end industrial
    # start military
    "explosive",
    # end military
    # diagnostic or lab
    "(?:.* )?contrast",
    "(?:.* )?screen",
    "(?:.* )?media",
    "(?:.* )?culture",
    "(?:.* )?polymerase chain reaction",
    "(?:.* )?test(?:ing)?",
    "(?:.* )?detect",
    "(?:.* )?diagnostic",
    "(?:.* )?diagnosis",
    "(?:.* )?analyt",  # analyte
    "reaction (?:vessel|mixture)",
    "(?:.* )?assay",
    "(?:.* )?microarray",
    "prognosticat",
    "(?:.* )?scopy" "(?:.* )?reagent",
    # end diagnostic
]

TEXT_FIELDS = frozenset(["title", "abstract"])
APPLICATIONS_TABLE = "applications"
ANNOTATIONS_TABLE = "annotations"
GPR_ANNOTATIONS_TABLE = "gpr_annotations"
GPR_PUBLICATIONS_TABLE = "gpr_publications"


ADHD = "Attention Deficit Hyperactivity Disorder"
ARTICULATION_DISORDER = "Articulation Disorder"
AMNESTIC_DISORDER = "Amnestic Disorder"
ANAESTHESIA = "Anaesthesia"
ANEMIA = "Anemia"
ANXIETY = "Anxiety"
ASPERGERS = "Aspergers"
AUTISM = "Autism"
BDI = "Bipolar I Disorder"
BDII = "Bipolar II Disorder"
BIPOLAR = "Bipolar Disorder"
BODY_DYSMORPHIA = "Body Dysmorphic Disorder"
BPD = "Borderline Personality Disorder"
BRIEF_PSYCHOTIC_DISORDER = "Brief Psychotic Disorder"
CELIAC = "Celiac Disease"
CYCLOTHYMIA = "Cyclothymia"
DEPRESSION = "Mental Depression"  # mental depression due to UMLS
DEVELOPMENTAL_DISORDER = "Developmental Disorder"
DELUSION = "Delusion"
DIARRHEA = "Diarrhea"
DYSTHYMIA = "Dysthymia"
EATING_DISORDER = "Eating Disorder"
GERD = "Gastroesophageal Reflux Disease"
GENERALIZED_ANXIETY_DISORDER = "Generalized Anxiety Disorder"
HEMATOLOGICAL_DISORDER = "Hematological Disorder"
HYPERSENSITIVITY = "Hypersensitivity"
INTERMITTENT_EXPLOSIVE_DISORDER = "Intermittent Explosive Disorder"
ISCHEMIA = "Ischemia"
MENTAL_DISORDER = "Mental Disorder"
MIGRAINE = "Migraine"
MOTOR_NEURON_DISEASE = "Motor Neuron Disease"
MOOD_DISRDER = "Mood Disorder"
NEURODEVELOPMENTAL_DISORDER = "Neurodevelopmental Disorder"
NPD = "Narcissistic Personality Disorder"
DISSASOCIATIVE_IDENTITY_DISORDER = "Dissociative identity disorder"
NEUROSIS = "Neurosis"
OCD = "Obsessive-Compulsive Disorder"
OPPOSITIONAL_DEFIANT_DISORDER = "Oppositional Defiant Disorder"
PAIN_DISORDER = "Pain Disorder"
PANIC = "Panic Disorder"
PATHOGENIC_PAIN = "Pathogenic Pain"
PDD = "Premenstrual Dysphoric Disorder"
PERSONALITY_DISORDER = "Personality Disorder"
PHOBIA = "Phobia"
PHOTOSENSITIVITY = "Photosensitivity"
PSYCHIATRIC_DISORDER = "Psychiatric Disorder"
PSYCHOTIC_DISORDER = "Psychotic Disorder"
PTSD = "Post-Traumatic Stress Disorder"
REPRODUCTIVE_DISORDER = "Reproductive Disorder"
SAD = "Seasonal Affective Disorder"
SCHIZOPHRENIA = "Schizophrenia"
SCHIZOPHRENIFORM_DISORDER = "Schizophreniform Disorder"
SCHIZOAFFECTIVE_DISORDER = "Schizoaffective Disorder"
SEXUAL_DISORDER = "Sexual Disorder"
SLEEP_APNEA = "Sleep Apnea"
SLEEP_DISORDER = "Sleep Disorder"
SOCIOPATHY = "Antisocial Personality Disorder"
STRESS_DISORDER = "Stress Disorder"
SUBSTANCE_ABUSE = "Substance Abuse"
SUBSTANCE_PSYCHOSIS = "Substance-Induced Psychotic Disorder"
TIC_DISORDER = "Tic Disorder"

SYNONYM_MAP = {
    "acute stress disease": STRESS_DISORDER,
    "alcohol use disease": SUBSTANCE_ABUSE,
    "amnestic disease": AMNESTIC_DISORDER,
    "anaemia of chronic disease": ANEMIA,
    "anaesthetic": ANAESTHESIA,
    "anaesthesia": ANAESTHESIA,
    "antisocial personality disease": SOCIOPATHY,
    "articulation disease": ARTICULATION_DISORDER,
    "autism spectrum disease": AUTISM,
    "autism disease": AUTISM,
    "autistic disease": AUTISM,
    "aspergers disease": ASPERGERS,
    "asperger syndrome": ASPERGERS,
    "aspergers syndrome": ASPERGERS,
    "asperger\\'s disease": ASPERGERS,
    "attention deficit hyperactivity disease": ADHD,
    "attention deficit/hyperactivity disease": ADHD,
    "attention deficit disorder with hyperactivity": ADHD,
    "anxiety": ANXIETY,
    "anxiety disease": GENERALIZED_ANXIETY_DISORDER,
    "bipolar disease": BIPOLAR,
    "bipolar i disease": BDI,
    "bipolar ii disease": BDII,
    "body dysmorphic disease": BODY_DYSMORPHIA,
    "borderline personality disease": BPD,
    "celiac disease": CELIAC,
    "coeliac disease": CELIAC,
    "combat disease": PTSD,  # ??
    "communication disease": "communication disorder",
    "cyclothymic disease": CYCLOTHYMIA,
    "generalised anxiety disease": GENERALIZED_ANXIETY_DISORDER,
    "generalized anxiety disease": GENERALIZED_ANXIETY_DISORDER,
    "delusional disease": DELUSION,
    "depressive disease": DEPRESSION,
    "depressed mood": DEPRESSION,
    "depressive symptom": DEPRESSION,
    "depressive": DEPRESSION,
    "dependence": SUBSTANCE_ABUSE,
    "diarrhoea": DIARRHEA,
    "dysthymic disease": DYSTHYMIA,
    "dissociative identity disease": DISSASOCIATIVE_IDENTITY_DISORDER,
    "dissociative disease": DISSASOCIATIVE_IDENTITY_DISORDER,
    "drug dependence": SUBSTANCE_ABUSE,
    "eating disease": EATING_DISORDER,
    "effect on cardiovascular disease": "Cardiovascular disease",
    "female reproductive system disease": REPRODUCTIVE_DISORDER,
    "gastrooesophageal reflux disease": GERD,
    "haemorrhagic disease": "Hemorrhagic disease",
    "haematological disease": HEMATOLOGICAL_DISORDER,
    "haemochromatosis": "Hemochromatosis",
    "hypersensitivity reaction disease": HYPERSENSITIVITY,
    "hypomania": BDII,
    "intermittent explosive disease": INTERMITTENT_EXPLOSIVE_DISORDER,
    "ischaemic disease": ISCHEMIA,
    "ischaemia": ISCHEMIA,
    "manic and bipolar mood disorders and disturbance": BIPOLAR,
    "major depression": DEPRESSION,
    "major depressive disease": DEPRESSION,
    "mental disease": MENTAL_DISORDER,
    "mood disease": MOOD_DISRDER,
    "middle ear disease": "Middle ear disorder",
    "migraine disorders": MIGRAINE,
    "motor neurone disease": MOTOR_NEURON_DISEASE,
    "multiple personality disease": DISSASOCIATIVE_IDENTITY_DISORDER,
    "movement disease": "movement disorder",
    "narcissistic personality disease": NPD,
    "neurotic disease": NEUROSIS,
    "neurotic disorder": NEUROSIS,
    "neurodevelopmental disease": NEURODEVELOPMENTAL_DISORDER,
    "obsessive-compulsive disease": OCD,
    "pain disease": PAIN_DISORDER,
    "panic disease": PANIC,
    "panic attacks and disease": PANIC,
    "pathogenic pain disease": PATHOGENIC_PAIN,
    "penicillins": "penicillin",
    "pervasive developmental disease": DEVELOPMENTAL_DISORDER,
    "personality disease": PERSONALITY_DISORDER,
    "photosensitivity disease": PHOTOSENSITIVITY,
    "phobic disease": PHOBIA,
    "post-traumatic stress disease": PTSD,
    "premenstrual dysphoric disease": PDD,
    "psychosexual disease": SEXUAL_DISORDER,
    "psychotic disease": PSYCHOTIC_DISORDER,
    "psychiatric disease": PSYCHIATRIC_DISORDER,
    "oppositional defiant disease": OPPOSITIONAL_DEFIANT_DISORDER,
    "reading disease": "Reading disorder",
    "schizoaffective disease": SCHIZOAFFECTIVE_DISORDER,
    "schizophreniform disease": SCHIZOPHRENIFORM_DISORDER,
    "brief psychotic disease": BRIEF_PSYCHOTIC_DISORDER,
    "schizophrenia and other psychotic disease": PSYCHOTIC_DISORDER,
    "seasonal affective disease": SAD,
    "sexual arousal disease": SEXUAL_DISORDER,
    "sexual desire disease": SEXUAL_DISORDER,
    "sleep disease": SLEEP_DISORDER,
    "shared psychotic disease": PSYCHOTIC_DISORDER,
    "sleep apnea syndrome": SLEEP_APNEA,
    "sleep apnoea syndrome": SLEEP_APNEA,
    "somatoform disease": "Somatoform disorder",
    "specific developmental disease": DEVELOPMENTAL_DISORDER,
    "stress disease": STRESS_DISORDER,
    "substance related disease": SUBSTANCE_ABUSE,
    "substance-related disease": SUBSTANCE_ABUSE,
    "substance-induced psychotic disease": SUBSTANCE_PSYCHOSIS,
    "tic disease": TIC_DISORDER,
    "transient tic disease": TIC_DISORDER,
}
