org: kristinalindquist
app: biosymbolics-pipeline
service: biosymbolics-pipeline

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  environment:
    GOOGLE_CLOUD_PROJECT: fair-abbey-386416
    MONGO_URI: mongodb+srv://kristin:LcVacKsgrZ6EQ7N8@biosymbolics.i6psynp.mongodb.net/
    OPENAI_API_KEY: ${ssm:/biosymbolics/pipeline/openai/api_key}
    PYTHONPATH: ./src:.
    SEC_API_KEY: ${ssm:/biosymbolics/pipeline/sec/api_key}
    TOKENIZERS_PARALLELISM: False


functions:
  search-patents:
    handler: handlers.patents.search
    layers:
      - Ref: PythonRequirementsLambdaLayer
  autocomplete-patents:
    handler: handlers.patents.autocomplete
    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements

package:
  # individually: true
  exclude:
    - patent_model_checkpoints/**
    - lib/**
    - data/**
    - storage/**
    - .mypy_cache/**
    - "**/__pycache__/**"
    - .pytest_cache/**
    - node_modules/**
    - package-lock.json
    - src/scripts/**
    - "**/test/**"
    - "*.pt"
    - ".requirements.zip"

custom:
  pythonRequirements:
    # dockerizePip: true
    # zip: true
    slim: true
    slimPatterns:
      - "**/__pycache__/**"
    fileName: src/handlers/requirements.txt
    layer: true
    noDeploy:
      - pytest
