org: kristinalindquist
app: biosymbolics-pipeline
service: biosymbolics-pipeline

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  timeout: 300
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: "arn:aws:ssm:*:*:parameter/biosymbolics/pipeline/*"
  apiGateway:
    apiKeys:
      - free:
          - ${ssm:/biosymbolics/pipeline/api/free-key}
      - paid:
          - ${ssm:/biosymbolics/pipeline/api/paid-key}
    usagePlan:
      - free:
          quota:
            limit: 50
            period: DAY
      - paid:
          quota:
            limit: 100
            period: DAY
  environment:
    GOOGLE_CLOUD_PROJECT: fair-abbey-386416
    MONGO_URI: mongodb+srv://kristin:LcVacKsgrZ6EQ7N8@biosymbolics.i6psynp.mongodb.net/
    OPENAI_API_KEY: ${ssm:/biosymbolics/pipeline/openai/api_key}
    PYTHONPATH: ./src:./:/opt/python:/opt/python/lib/python3.10/site-packages
    SEC_API_KEY: ${ssm:/biosymbolics/pipeline/sec/api_key}
    TOKENIZERS_PARALLELISM: False


functions:
  search-patents:
    events:
      - http:
          path: patents/search
          method: get
          cors: true
    handler: src.handlers.patents.search
    layers:
      - Ref: PythonRequirementsLambdaLayer
  autocomplete-patents:
    events:
      - http:
          path: terms/search
          method: get
          cors: true
    handler: src.handlers.patents.autocomplete
    layers:
      - Ref: PythonRequirementsLambdaLayer
  describe-terms:
    events:
      - http:
          path: terms/describe
          method: get
          cors: true
    url:
      invokeMode: RESPONSE_STREAM
    handler: src.handlers.patents.describe
    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements

package:
  # individually: true
  patterns:
    - "!**"
    - "src/**"
    - "!**/__pycache__/**"
    - "!src/scripts/**"
    - "!**/test/**"

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    slimPatternsAppendDefaults: true
    slimPatterns:
      - "**/__pycache__/**"
      - "**/tests/**"
    fileName: src/handlers/requirements.txt
    layer: true
    noDeploy:
      - pytest

resources:
  Resources:
    RDSCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername: ${ssm:/biosymbolics/pipeline/database/patents/main_username}
        MasterUserPassword: ${ssm:/biosymbolics/pipeline/database/patents/main_password}
        DatabaseName: ${ssm:/biosymbolics/pipeline/database/patents/db_name}
        Engine: aurora-postgresql
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 4
          MinCapacity: 2
          SecondsUntilAutoPause: 300
        EnableHttpEndpoint: true
        StorageEncrypted: true
