"""
Pattern constants
"""
__all__ = [
    "BIOLOGIC_INFIXES",
    "BIOLOGIC_SUFFIXES",
    "MOA_INFIXES",
    "MOA_SUFFIXES",
    "SMALL_MOLECULE_INFIXES",
    "SMALL_MOLECULE_SUFFIXES",
]

from .biologics import BIOLOGIC_INFIXES, BIOLOGIC_SUFFIXES
from .moa import MOA_INFIXES, MOA_SUFFIXES
from .small_molecules import SMALL_MOLECULE_INFIXES, SMALL_MOLECULE_SUFFIXES
