"""
Pattern constants
"""
__all__ = [
    "BIOLOGIC_INFIXES",
    "BIOLOGIC_SUFFIXES",
    "EFFECTS",
    "INDICATION_REGEXES",
    "INDICATION_MODIFIER_REGEXES",
    "MOA_INFIXES",
    "MOA_SUFFIXES",
    "SMALL_MOLECULE_INFIXES",
    "SMALL_MOLECULE_SUFFIXES",
]

from .biologics import BIOLOGIC_INFIXES, BIOLOGIC_SUFFIXES
from .indication import INDICATION_MODIFIER_REGEXES, INDICATION_REGEXES
from .moa import EFFECTS, MOA_INFIXES, MOA_SUFFIXES
from .small_molecules import SMALL_MOLECULE_INFIXES, SMALL_MOLECULE_SUFFIXES
