"""
Constants related to Biologic drugs
"""

BIOLOGIC_BASE_TERMS: list[str] = [
    "(?:(?:glyco|fusion)[ -]?)?proteins?(?: binding)?",
    "(?:poly)peptides?(?: binding)?",
    "(?:poly|di|tri)?nucleo[ts]ides?(?: binding)?",
    "(?:receptor |protein )?ligands?(?: binding| that bind)?",
    "(?:dna |nucleic acid |antibody )?(?:fragments?|sequences?)(?: binding| that bind)?",
    "aggregate",
    "allele",
    "(?:amino |fatty |(?:poly|di|tri)?nucleic )acid",
    "(?:neo)?antigen",
    "antigen[ -]binding fragment",
    "antigen presenting cell",
    "aptamer",
    "anion",
    "(?:auto)?antibod(?:ie|y)",
    "adc",
    "antibod(?:y|ie)",
    "antibody[ -]?drug[ -]conjugate",
    "(?:antibody |dna |rna )?molecules?(?: binding)?",
    "bio(?:material|chemical)",
    "biosimilar",
    "bcma(?: nke)?",
    "car[- ]?(?:t|nk)",
    "chimeric antigen receptor",
    "chemotherap(?:y|ie)",  # not necessary biologic, more class/descriptive
    "(?:adoptive )?cell(?: tranfer)?(?: therap(?:y|ie))?",  # cell disease
    "clone",
    "complement(?: component)?",
    "conjugate",
    "(?:cell )?culture",
    "cytokine",
    "decomposition",
    "(?:recombinant )?dna",
    "epitope",
    "exosome",
    "enzyme",
    "(?:gene )?expression",
    "fab(?: region)?",
    "factor [ivx]{1,3}",
    "fc(?:[- ]fusion )?(?: protein)?",
    "fus(?:ed|ion)",
    "gene",
    "(?:growth )?factor",
    "(?:hairpin|micro|messenger|sh|si|i|ds|m|hp|recombinant|double[- ]?stranded|small[- ]?interfering|guide)?[ -]?(?:rna|ribonucleic acid)(?: molecule| sequence)?",
    "(?:trans)?gene",
    "hormone",
    "immun[io][zs](?:ation|ing|e|logical|therapy|genic)",
    "insulin",
    "interferon",
    "interleukin",
    "isoform",
    "(?:phospho[ -]?|sphingo[ -]?)?lipid",
    "keratin",
    "(?:dehydratase|esterase|hydrolase|ligase|mutase|oxidase|protease|synthase|transferase|transcriptase|reductase|kinase|nuclease)",  # some enzymes
    "(?:co[ -]?)?(?:di|mono|poly|oligo)mer",
    "(?:natural killer|nkt|nkc)(?: cells?)?",
    "lignin",
    "liposome",
    "(?:macro|bio)?[ -]?molecule",
    "(?:(?:neuro|immuno)[- ]?)?modulat(?:or|ion|ing|e)s?(?: binding)?",
    "motif",
    "mutein",
    "mutation",
    "(?:oligo[ -])?nucleotides?(?: sequence)?",
    "(?:poly[ -]?)?peptides?(?: sequence)?",
    "plasmid",
    "protein",
    "recombinant",
    "receptor",  # ??
    "recognizer",
    "(?:recombinant|attenuated|antibod(?:y|ies)|inhibit|anti|chimeric|synthetic).*virus",
    "scaffold",
    "scfv",  # single-chain variable fragment
    "sequence",
    "(?:expression )?vector",
    "stem cell",
    "strand",
    "toxin",
    "(?:tumor[- ]?infiltrating )?lymphocyte",
    "(?:(?:immuno|gene)[ -]?)?therap(?:y|ie)",
    "transcription(?: factor)?",
    "(?:(?:[t|b][ -]cell )engag(?:er|ing|e|ment)(?: receptor)?|tce(?:r))",
]
