HIGH_LIKELIHOOD_DEVICES = [
    ".*wearable.*",
    "(?:.* )?video",
    ".*electronic.*",
    "(?:.* )?dressing",
    "(?:.* )?cannula",
    "(?:.* )?(?:back)?rest",
    "(?:.*[ -]?)?inject(?:or)?",  # autoinjector
    "(?:.* )?packag(?:ing|ed)(?: .*)?",  # packaging
    "(?:.*)?needl",  # microneedle
    "(?:.* )?bolus",
    "(?:.* )?retainer",
    "(?:.* )?infusion pump",
    "(?:.* )?pacemaker",
    "(?:.* )?glass",
    "(?:.* )?rubber",  # ??
    "(?:.* )?tank",
    "(?:.* )?computer.*",
    "(?:.* )?latch",
    "(?:.* )?manifold",
    "(?:.* )?headgear",
    "(?:.* )?clip",
    "(?:.* )?belt",
    "(?:.* )?pivot",
    "(?:.* )?mask",
    "(?:.* )?board",
    "(?:.* )?bridge",
    "(?:.* )?cuff",
    "(?:.* )?pouch",
    "(?:.* )?container",
    "(?:.* )?fiber",  # TODO could be bio
    "(?:.* )?conductor",
    "(?:.* )?connector",
    "(?:.* )?effector",
    "(?:.* )?tape",
    "(?:.* )?inlet",
    "(?:.* )?outlet",
    "(?:.* )?strip",  # e.g. test strip
    "(?:.* )?solid state",
    "(?:.*)?wire",  # e.g. guidewire
    "(?:.* )?bed",
    "(?:.* )?switch",  # could potentially be biological
    "(?:.* )?prosthetic",
    "(?:.* )?equipment",
    "(?:.* )?generator",
    "(?:.* )?(?:micro)?channel",
    "impression material",
    "(?:.* )?light[ -]?emitt(?:er|ing)s?.*",
    "(?:.* )?cathode",
    "(?:.* )?delivery system",
    "(?:.* )?dielectric",
    "(?:.* )?roller",
    "building material",
    "(?:.* )?mandrel",
    "(?:.* )?stylet",
    "(?:.* )?coupling",
    "(?:.* )?attachment",
    "(?:.* )?shaft",
    "(?:.* )?aperture",
    "(?:.* )?(?:bio)?sensor",
    "(?:.* )?conduit",
    "(?:.* )?endoscope",
    "(?:.* )?article",
    "(?:.* )?nozzle",
    "(?:.* )?plastic",
    "(?:.* )?holder",
    "(?:.* )?flange",
    "(?:.* )?circuit",
    "(?:.* )?liner",
    "(?:.* )?paper",
    "(?:.* )?light",  # light chain? (bio)
    "(?:.* )?solar cell.*",
    "(?:.* )?ground",
    "(?:.* )?waveform",
    "(?:.* )?tool",
    "(?:.* )?centrifug",
    "(?:.* )?centrifugat",
    "(?:.* )?current",
    "(?:.* )?surfac",
    "(?:.* )?recording medium",
    "(?:.* )?field",
    "(?:.* )?element",  # e.g. locking element # TODO probably excessive
    "(?:.* )?garment",
    "(?:.* )?mou?ld(?: .*)?",  # molding, moulded, molded product
    "(?:.* )?napkin",
    "(?:.* )?anvil",
    "(?:.* )?implant.*",
    "(?:.* )?wheelchair",
    "(?:.* )?wall",
    "(?:.* )?wheel",
    "(?:.* )?manipulat",  # manipulator
    "(?:.* )?gasket",
    "(?:.* )?ratchet",
    "(?:.* )?syringe(?: .*)?",
    "(?:.* )?canist",
    "(?:.* )?slide",
    "(?:.* )?tether",
    "(?:.* )?spectromet",
    "(?:.* )?diaper",
    "(?:.* )?coil",
    "(?:.* )?apparatus(?:es)?",
    "(?:.* )?waveguide",
    "(?:.* )?implant",
    "(?:.* )?rod",
    "(?:.* )?cushion",
    "(?:.* )?trocar",
    "(?:.* )?liquid crystal(?: .*)?",
    "(?:.* )?prosthesis",
    "(?:.* )?catheter.*",
    "(?:.* )?(?:bio[ -]?)?film",
    "(?:.* )?hinge",
    "(?:.* )?instrument",
    "(?:.* )?vessel",
    "(?:.* )?device(?: .*)?",
    "(?:.* )?motor",
    "(?:.* )?electrode",
    "(?:.* )?camera",
    "(?:.* )?mouthpiec",
    "(?:.* )?transduc",
    "(?:.* )?toothbrush",
    "(?:.* )?sutur",
    "(?:.* )?stent",
]
# for use in patents; might need adjustment to be more generally applicable.
DEVICE_RES = [
    *HIGH_LIKELIHOOD_DEVICES,
    "(?:.* )?linkage",  # ??
    "(?:.* )?head",
    "(?:.* )?source",  # TODO
    "(?:.* )?window",
    "(?:.* )?body",
    "(?:.* )?sheath",
    "(?:.* )?compartment",
    "(?:.* )?table",
    "(?:.* )?receptacle",
    "(?:.* )?display",
    "(?:.*[ -])?scale",
    "(?:.* )?imag",  # imaging
    "(?:.* )?imag(?:e|ing) (?:.*)?",
    "(?:.* )?port",
    "(?:.* )?cutt(?:er|ing)",
    "(?:.* )?seperat",
    "(?:.* )?(?:bio)?reactor",
    "(?:.* )?program",
    "(?:.* )?plat",  # plate
    "(?:.* )?dispens",
    "(?:.* )?tip",
    "(?:.* )?prob",  # probe
    "(?:.* )?fasten",
    "(?:.* )?spacer",
    "(?:.* )?radiat",
    "(?:.* )?actuat",
    "(?:.* )?clamp",
    "(?:.* )?fabric",
    "(?:.* )?sens",  # sensor
    "(?:.* )?waf",  # wafer
    "(?:.* )?tampon",
    "(?:.* )?(?:top)?sheet",
    "(?:.* )?pad",
    "(?:.* )?strut",
    "(?:.* )?capacit",
    "(?:.* )?reservoir",
    "(?:.* )?housing",
    "(?:.* )?diaphragm",
    "(?:.* )?cartridge",
    "(?:.* )?plunger",
    "(?:.* )?ultrasound(?: .*)?",
    "(?:.* )?piston",
    "(?:.* )?balloon",
    "(?:.* )?stapl",
    "(?:.* )?engine",
    "(?:.* )?wave",
    "(?:.* )?pump",
    "(?:.* )?article",
    "(?:.* )?screw",
    "(?:.* )?cytomet",
    "(?:.* )?appliance",
    "(?:.* )?blow",
    "(?:.* )?tube",
    "(?:.* )?lancet",
    "(?:.* )?capsul",
    "(?:.* )?valv",
    "(?:.* )?bladder",
    "(?:.* )?compressor",
    "(?:.* )?forcep",
    "(?:.* )?splitt",  # splitter
    "(?:.* )?battery",
    "(?:.* )?blad",  # blade
    "(?:.* )?machine",
    "(?:.* )?applicat",
    "(?:.* )?monit",
    "(?:.* )?irrigat",
    "(?:.* )?accelerat",
    "(?:.* )?indicat",
    "(?:.* )?pump",
    "(?:.* )?chamber",
    "(?:.* )?sponge",
    "(?:.* )?textile",
    "(?:.* )?lead",
    "(?:.* )?block",  # TODO: procedure?
    ".*graphy",
    "acceleromet",
    "mobile",
    "core[ -]?shell",  # what is this?
    "stop(?:per)?",
    "electrical stimulat",
    ".*mechanical.*",
    ".*transceiver",
    ".*piezoelectric.*",
    ".*ultrasonic.*",
    "impeller",
    "transmit",
    "slider",
    "abutment",
    "interferometer",
    "fastening mean",
    "piezoelectric.*",
    "handpiece",
    "reagent kit",
    "(?:.* )?diode",
    "centrifugal force",
    "robot.*",
    "(?:fuel|electrochemical) cell",
    # "(?:.* )?generator",??
]
