"""
Constants for the patents client.
"""
from constants.patterns.moa import ACTIONS


COMPOSITION_OF_MATTER_IPC_CODES = [
    "C01",  # inorganic chemistry
    "C07",  # organic chemistry
    "C08",  # organic macromolecular compounds
    "C12",  # biochemistry; beer; spirits; wine; vinegar; microbiology; enzymology; mutation or genetic engineering
]

# less likely
# "C09",  # dyes; paints; polishes; natural resins; adhesives; compositions not otherwise provided for
# "C10",  # petroleum, gas or coke industries; technical gases containing carbon monoxide; fuels; lubricants; peat
# "C11",  # ANIMAL OR VEGETABLE OILS, FATS, FATTY SUBSTANCES OR WAXES; FATTY ACIDS THEREFROM; DETERGENTS; CANDLES

# C07D217/04 - process for preparing
# C07C317/44 - method of use and making
# C07D405/12 - process for preparing
# C07C213/00 - transdermal delivery
# C07D405/12 - process for preparing
# C12Q1/68 - methods for characterization, monitoring, and treatment
# C12Q1/68 - method for predicting
# C12Q1/68 - pcr for detection
# C07D405/12, C07D405/14, C07D401/14 - process for preparing
# C07C215/08, C07C213/02 - process for preparing
# C07D333/70, C07D409/12 - methods of preparing
# C07D295/096 - process for preparing
# C07D311/26, C07C15/14, C07C15/12, C07C39/16, C07F15/00, C07F15/02, C07F15/04 - good
# C07D487/04, C07D471/04, C07D519/00, C07D471/04, C07D487/04, C07D519/00, C07D513/04 - good
# C07D209/40, C07D305/08, C07D295/135, C07D471/10, C07D487/10, C07D213/64 - good
# C07D413/04, C07D409/14, C07C317/44, C07J9/00, C07J7/00 - composition of matter AND methods
# C12Q1/68 - method for selecting
# C12Q1/68 - methods, processes, devices for measurement


METHOD_OF_USE_IPC_CODES = [
    "A01N",  # Methods of using biocides or herbicides
    "A61B",  # Methods of using surgical instruments or devices
    "A61F",  # Methods of using implants or prostheses
    "A61K",  # Preparations for medical, dental, or toilet purposes.
    "A61M",  # Methods of using catheters or other medical devices
    "A61P",  # Specific therapeutic activity of chemical compounds or medicinal preparations.
    "C07K",  # Methods of using immunoglobulins
    "C12N",  # Methods of using microorganisms or enzymes in food or beverage production
    "G01N",  # Methods of using immunoassays or other analytical techniques
    "H04N",  # Methods of using video or multimedia systems
    "H04R",  # Methods of using audio or acoustic systems
]

COMPANY_NAME_SUPPRESSIONS = [
    "AB",
    "AG",
    "BIOSCIENCE",
    "BIOTEC",
    "BIOTECH",
    "CHEM",
    "CO",
    "COMPANY",
    "COOP",
    "CORP",
    "CORPORATION",
    "DEV",
    "DIAGNOSTIC",
    "FARM",
    "FARMA",
    "GROUP",
    "GMBH",
    "HEALTHCARE",
    "INC",
    "INSTITUTE",
    "INT",
    "IP",
    "KG",
    "LLC",
    "LP",
    "LTD",
    "MEDICAL",
    "NETWORK",
    "NV",
    "PATENT",
    "PHARM",
    "PHARMA",
    "PHARMACEUTICA",
    "PHARMACEUTICAL",
    "PHARAMACEUTICAL",
    "PTY",
    "SCIENCE",
    "SA",
    "SPA",
    "SYSTEM",
    "THE",
    "THERAPEUTIC",
]

COUNTRIES = [
    "DEUTSCHLAND",
    "EU",
    "IRELAND",
    "UK",
    "USA",
]

MAX_PATENT_LIFE = 20

PATENT_ATTRIBUTE_MAP = {
    "COMBINATION": ["combination"],
    "COMPOUND_OR_MECHANISM": [
        "composition",
        "compound",
        "composition",
        "derivative",
        "substitute",
        *ACTIONS,
    ],
    "DIAGNOSTIC": [
        "diagnosis",
        "diagnostic",
        "biomarker",
        "detection",
        "imaging",
        "marker",
        "monitoring",
        "risk score",
        "sensor",
        "testing",
    ],
    "FORMULATION": ["formulation", "form"],
    "METHOD": ["method", "procedure", "use"],
    "NOVEL": ["novel"],
    "PREPARATION": ["preparation"],
    "PROCESS": ["process", "sythesis", "system"],
}

PATENT_ATTRIBUTES = dict([(k, k) for k in PATENT_ATTRIBUTE_MAP.keys()])

ADHD = "Attention Deficit Hyperactivity Disorder"
ARTICULATION_DISORDER = "Articulation Disorder"
ANAESTHESIA = "Anaesthesia"
ANEMIA = "Anemia"
ANXIETY = "Anxiety"
ASPERGERS = "Aspergers"
AUTISM = "Autism"
BDI = "Bipolar I Disorder"
BDII = "Bipolar II Disorder"
BIPOLAR = "Bipolar Disorder"
BODY_DYSMORPHIA = "Body Dysmorphic Disorder"
BPD = "Borderline Personality Disorder"
CELIAC = "Celiac Disease"
DEPRESSION = "Depression"
DEVELOPMENTAL_DISORDER = "Developmental Disorder"
DELUSION = "Delusion"
DIARRHEA = "Diarrhea"
GERD = "Gastroesophageal Reflux Disease"
HEMATOLOGICAL_DISORDER = "Hematological Disorder"
HYPERSENSITIVITY = "Hypersensitivity"
INTERMITTENT_EXPLOSIVE_DISORDER = "Intermittent Explosive Disorder"
ISCHEMIA = "Ischemia"
MENTAL_DISORDER = "Mental Disorder"
MIGRAINE = "Migraine"
MOTOR_NEURON_DISEASE = "Motor Neuron Disease"
MOOD_DISRDER = "Mood Disorder"
NEURODEVELOPMENTAL_DISORDER = "Neurodevelopmental Disorder"
NPD = "Narcissistic Personality Disorder"
DISSASOCIATIVE_IDENTITY_DISORDER = "Dissociative identity disorder"
NEUROSIS = "Neurosis"
OCD = "Obsessive-Compulsive Disorder"
OPPOSITIONAL_DEFIANT_DISORDER = "Oppositional Defiant Disorder"
PAIN_DISORDER = "Pain Disorder"
PATHOGENIC_PAIN = "Pathogenic Pain"
PDD = "Premenstrual Dysphoric Disorder"
PERSONALITY_DISORDER = "Personality Disorder"
PHOBIA = "Phobia"
PHOTOSENSITIVITY = "Photosensitivity"
PSYCHIATRIC_DISORDER = "Psychiatric Disorder"
PSYCHOTIC_DISORDER = "Psychotic Disorder"
PTSD = "Post-Traumatic Stress Disorder"
REPRODUCTIVE_DISORDER = "Reproductive Disorder"
SAD = "Seasonal Affective Disorder"
SCHIZOPHRENIA = "Schizophrenia"
SCHIZOAFFECTIVE_DISORDER = "Schizoaffective Disorder"
SEXUAL_DISORDER = "Sexual Disorder"
SLEEP_APNEA = "Sleep Apnea"
SLEEP_DISORDER = "Sleep Disorder"
SOCIOPATHY = "Antisocial Personality Disorder"
STRESS_DISORDER = "Stress Disorder"
SUBSTANCE_ABUSE = "Substance Abuse"
SUBSTANCE_PSYCHOSIS = "Substance-Induced Psychotic Disorder"
TIC_DISORDER = "Tic Disorder"

# graft versus host disease vs graft-versus-host disease vs vs
# dysthymic disease
# panic disease
# paranoid personality disease
# schizoid personality disease
# schizotypal personality disease
# brief psychotic disease
# amnestic disease
# dissociative disease
# eating disease
# adjustment disease
# mania
# avoidant personality disease
# cyclothymic disease
# leukaemia
# leukemia, myeloid, acute vs acute myeloid leukaemia
SYNONYM_MAP = {
    "acute stress disease": STRESS_DISORDER,
    "alcohol use disease": SUBSTANCE_ABUSE,
    "anaemia of chronic disease": ANEMIA,
    "anaesthetic": ANAESTHESIA,
    "anaesthesia": ANAESTHESIA,
    "antisocial personality disease": SOCIOPATHY,
    "articulation disease": ARTICULATION_DISORDER,
    "autism spectrum disease": AUTISM,
    "autism disease": AUTISM,
    "autistic disease": AUTISM,
    "aspergers disease": ASPERGERS,
    "asperger syndrome": ASPERGERS,
    "aspergers syndrome": ASPERGERS,
    "asperger\\'s disease": ASPERGERS,
    "attention deficit hyperactivity disease": ADHD,
    "attention deficit/hyperactivity disease": ADHD,
    "attention deficit disorder with hyperactivity": ADHD,
    "anxiety": ANXIETY,
    "anxiety disease": ANXIETY,
    "bipolar disease": BIPOLAR,
    "bipolar i disease": BDI,
    "bipolar ii disease": BDII,
    "body dysmorphic disease": BODY_DYSMORPHIA,
    "borderline personality disease": BPD,
    "celiac disease": CELIAC,
    "coeliac disease": CELIAC,
    "combat disease": PTSD,  # ??
    "communication disease": "communication disorder",
    "generalised anxiety disease": ANXIETY,
    "generalized anxiety disease": ANXIETY,
    "delusional disease": DELUSION,
    "depressive disease": DEPRESSION,
    "depressed mood": DEPRESSION,
    "depressive symptom": DEPRESSION,
    "dependence": SUBSTANCE_ABUSE,
    "diarrhoea": DIARRHEA,
    "dissociative identity disease": DISSASOCIATIVE_IDENTITY_DISORDER,
    "drug dependence": SUBSTANCE_ABUSE,
    "effect on cardiovascular disease": "Cardiovascular disease",
    "female reproductive system disease": REPRODUCTIVE_DISORDER,
    "gastrooesophageal reflux disease": GERD,
    "haemorrhagic disease": "Hemorrhagic disease",
    "haematological disease": HEMATOLOGICAL_DISORDER,
    "haemochromatosis": "Hemochromatosis",
    "hypersensitivity reaction disease": HYPERSENSITIVITY,
    "hypomania": BDII,
    "intermittent explosive disease": INTERMITTENT_EXPLOSIVE_DISORDER,
    "ischaemic disease": ISCHEMIA,
    "ischaemia": ISCHEMIA,
    "major depression": DEPRESSION,
    "major depressive disease": DEPRESSION,
    "mental disease": MENTAL_DISORDER,
    "mood disease": MOOD_DISRDER,
    "middle ear disease": "Middle ear disorder",
    "migraine disorders": MIGRAINE,
    "motor neurone disease": MOTOR_NEURON_DISEASE,
    "multiple personality disease": DISSASOCIATIVE_IDENTITY_DISORDER,
    "movement disease": "movement disorder",
    "narcissistic personality disease": NPD,
    "neurotic disease": NEUROSIS,
    "neurotic disorder": NEUROSIS,
    "neurodevelopmental disease": NEURODEVELOPMENTAL_DISORDER,
    "obsessive-compulsive disease": OCD,
    "pain disease": PAIN_DISORDER,
    "pathogenic pain disease": PATHOGENIC_PAIN,
    "penicillins": "penicillin",
    "pervasive developmental disease": DEVELOPMENTAL_DISORDER,
    "personality disease": PERSONALITY_DISORDER,
    "photosensitivity disease": PHOTOSENSITIVITY,
    "phobic disease": PHOBIA,
    "post-traumatic stress disease": PTSD,
    "premenstrual dysphoric disease": PDD,
    "psychosexual disease": SEXUAL_DISORDER,
    "psychotic disease": PSYCHOTIC_DISORDER,
    "psychiatric disease": PSYCHIATRIC_DISORDER,
    "oppositional defiant disease": OPPOSITIONAL_DEFIANT_DISORDER,
    "reading disease": "Reading disorder",
    "schizoaffective disease": SCHIZOAFFECTIVE_DISORDER,
    "schizophrenia and other psychotic disease": PSYCHOTIC_DISORDER,
    "seasonal affective disease": SAD,
    "sexual arousal disease": SEXUAL_DISORDER,
    "sexual desire disease": SEXUAL_DISORDER,
    "sleep disease": SLEEP_DISORDER,
    "shared psychotic disease": PSYCHOTIC_DISORDER,
    "sleep apnea syndrome": SLEEP_APNEA,
    "sleep apnoea syndrome": SLEEP_APNEA,
    "somatoform disease": "Somatoform disorder",
    "specific developmental disease": DEVELOPMENTAL_DISORDER,
    "stress disease": STRESS_DISORDER,
    "substance related disease": SUBSTANCE_ABUSE,
    "substance-related disease": SUBSTANCE_ABUSE,
    "substance-induced psychotic disease": SUBSTANCE_PSYCHOSIS,
    "tic disease": TIC_DISORDER,
    "transient tic disease": TIC_DISORDER,
}


# TO suppress
COMMON_ENTITY_NAMES = (
    "compounds",
    "",
    "antibodies",
    "proteins and genes",
    "nucleic acids",
    "chemical reaction",
    "effects",
    "antigens",
    "binding",
    "tissues",
    "polypeptide",
    "proteins",
    "alkyl group",
    "chemical substances by application",
    "ethyl acetate",
    "Enzymes",
    "preparation method",
    "methanol",
    "deoxyribonucleic acid",
    "salts",
    "gene expression",
    "inhibitory effect",
    "amino acids",
    "polynucleotide",
    "manufacturing process",
    "detection method",
    "amino acid",
    "biosynthetic process",
    "injection",
    "corresponding",
    "particle",
    "polymer",
    "ethanol",
    "antigen",
    "alpha amino acid group",
    "measurement",
    "substrate",
    "Nucleic acid sequence",
    "acetic acid ethyl ester",
    "layer",
    "analytical method",
    "Embryophyta",
    "receptors",
    "nitrogen",
    "carbon atoms",
    "blood",
    "methyl group",
    "gas",
    "tetrahydrofuran",
    "processed proteins & peptides",
    "reaction mixture",
    "bioassay",
    "optical",
    "aryl group",
    "catalyst",
    "hexane",
    "Neoplasm",
    "monoclonal antibodies",
    "synthesis reaction",
    "nucleotide group",
    "methylene dichloride",
    "synthesizing",
    "substituent group",
    "inhibitor",
    "nucleotide",
    "chemical reaction reagent",
    "carrier",
    "phenyl group",
    "membrane",
    "absorbent",
    "Blood",
    "silicium dioxide",
    "Ethyl acetate",
    "metal",
    "adhesive",
    "resin",
    "oil",
    "powder",
    "Oligonucleotide",
    "hydrogen atoms",
    "formulation",
    "imaging method",
    "EtOH",
    "modification reaction",
    "acetic acid",
    "modification",
    "diethyl ether",
    "fusion proteins",
    "implant",
    "stirring",
    "acetonitrile",
    "sodium hydroxide",
    "(ribonucleotides)n+m",
    "heterocyclic group",
    "ligand",
    "base",
    "fiber",
    "suspension",
    "halogens",
    "HCl",
    "heteroaryl group",
    "toluene",
    "primary amino group",
    "formation reaction",
    "response",
    "heat treatment",
    "therapeutic procedure",
    "modifying",
    "hydroxy group",
    "extract",
    "buffer",
    "mutation",
    "Saccharomyces cerevisiae",
    "Viruses",
    "fermentation",
    "insulin",
    "Homo sapiens",
    "alkoxy group" "Insulin",
    "Bone and Bones",
    "purification",
    "coating method",
    "coating agent",
    "oils",
    "DMSO-d6",
    "Bacteria",
    "insertion",
    "substitution reaction",
    "Skin",
    "intermediate",
    "phase",
    "glucose",
    "esters",
    "separation method",
    "chlorine",
    "halogen group",
    "matrix material",
    "D-Glucose",
    "complement",
    "cellulose",
    "enhancing",
    "Metazoa",
    "coupling reaction",
    "diagram",
    "Enzyme",
    "filtration",
    "coupling process",
    "coupling",
    "active ingredient",
    "ethyl group",
    "dichloromethane",
    "trifluoroacetic acid",
    "Complementary DNA",
    "(C1-C6) alkyl group",
    "in vitro",
    "cycloalkyl group",
    "acetone",
    "activation",
    "amplification",
    "diseases by infectious agent",
    "nucleic acid amplification method",
    "species",
    "inductive effect",
    "stimulation",
    "polyethylene glycol",
    "Serum",
    "aqueous solution",
    "capsule",
    "cooling",
    "chloroform",
    "Plasma",
    "interaction",
    "organic layer",
    "additive",
    "collagen",
    "lipids",
    "Collagen",
    "Messenger RNA",
    "potassium carbonate",
    "messenger RNA",
    "vaccines",
    "plastic",
    "calcium",
    "carbon dioxide",
    "regulatory",
    "pyridine",
    "glass",
    "administration",
    "amino acid group",
    "biological transmission",
    "ether",
    "extraction",
    "polysaccharide",
    "silica gel",
    "fatty acid",
    "silicon dioxide",
    "biotin",
    "microbiome",
    "surface-active agent",
    "dietary fatty acids",
    "sodium bicarbonate",
    "cleaning",
    "tablet",
    "amines",
    "brine",
    "absorption reaction",
    "Peptidases",
    "precursor",
    "polymerase chain reaction",
    "heteroatoms",
    "bead",
    "cyano group",
    "ions",
    "carbohydrates",
    "pathway",
    "alkenyl group",
    "analyte",
    "deuterated chloroform",
    "glycerol",
    "washing",
    "fusion",
    "carboxy group",
    "copolymer",
    "mediated",
    "atoms",
    "Mammalia",
    "emulsion",
    "hydrocarbons",
    "polyvinylpyrrolidone",
    "magnesium sulphate",
    "hybridization",
    "experimental method",
    "filtrate",
    "ingredient",
    "high performance liquid chromatography",
    "gelatin",
    "iron",
    "drying",
    "ultrasonography",
    "engineering process",
    "complementary DNA",
    "dependent",
    "organs",
    "nanoparticle",
    "genetic",
    "sealing",
    "cleavage reaction",
    "trifluoromethyl group",
    "copper",
    "Polyethylene glycol",
    "decreasing",
    "benzene",
    "magnesium stearate",
    "NaHCO3",
    "monomer",
    "lactic acid",
    "sampling",
    "microRNA",
    "dosage form",
    "growth",
    "evaluation",
    "lactose",
    "surgical procedure",
    "palladium",
    "Coding region",
    "Escherichia coli",
    "spectrum",
    "methylene chloride",
    "fatty acids",
    "food",
    "Acetic acid",
    "linker group",
    "ALB",
    "formic acid",
    "cellular",
    "binding agent",
    "transforming",
    "starting material",
    "infusion",
    "reflux",
    "sensitivity",
    "sodium sulphate",
    "hydrochloric acid",
    "citric acid",
    "liquid chromatography mass spectrometry",
    "propylene glycol",
    "sodium carbonate",
    "growth media",
    "prevention",
    "melting",
    "inspection",
    "composite material",
    "maintenance of location",
    "solvate",
    "supernatant",
    "comparative effect",
    "prodrug",
    "Glycine max",
    "prodrugs",
    "Glycine",
    "anti-sense",
    "glycerine",
    "phosphate",
    "cosmetic",
    "Starch",
    "oxidation reaction",
    "silicon",
    "liposome",
    "dye",
    "dimethylsulphoxide",
    "chromatography analysis",
    "sugar",
    "hydrogen peroxide",
    "zinc",
    "organic solvent",
    "Liver",
    "triethylamine",
    "hydroxypropyl methyl cellulose",
    "film",
    "toxicity",
    "diluting agent",
    "alginic acid",
    "drug carrier",
    "na2so4",
    "compression",
    "gold",
    "transcription",
    "polysiloxane",
    "(C1-C4) alkyl group",
    "Pain",
    "hydrophobic",
    "vehicle",
    "dispersion",
    "ascorbic acid",
    "amino group",
    "organic phase",
    "crude product",
    "detectable",
    "precipitate",
    "alkynyl group",
    "cyclic group",
    "Blood Vessels",
    "suppression",
    "iso-propanol",
    "protective",
    "oxidation",
    "Muscles",
    "diagnosis",
    "Lung",
    "porous material",
    "aryl alkyl group",
    "catabolic process",
    "illumination",
    "chimera",
    "granular material",
    "glycans",
    "platinum",
    "cardiac effect",
    "construction",
    "sterilization and disinfection",
    "raw material",
    "neutralization",
    "peripheral",
    "nitro group",
    "cell culture",
    "magnesium",
    "intravenous administration",
    "sterilising",
    "radicals",
    "benzyl group",
    "immunization",
    "immune response",
    "recovery",
    "body weight",
    "mannitol",
    "Protease",
    "DMSO",
    "argon",
    "spray",
    "tert-butyl group",
    "acids",
    "developmental process",
    "controlling effect",
    "pathogenic",
    "formaldehyde",
    "immunogen",
    "isopropyl group",
    "Sucrose",
    "displacement reaction",
    "Carbon black (E152)",
    "excitation",
    "microcrystalline cellulose",
    "survival",
    "dilution",
    "alkylene group",
    "potassium",
    "aerosol",
    "column chromatography",
    "fabric",
    "D-sucrose",
    "nontoxic",
    "amides",
    "foam",
    "conductor",
    "tumor cells",
    "iodine",
    "silver",
    "polymerization reaction",
    "polysaccharides",
    "biological sample",
    "elastomer",
    "visual effect",
    "concentrate",
    "methoxy group",
    "signaling",
    "isolation",
    "distillation",
    "acidificating",
    "polyurethane",
    "neural",
    "aliphatic group",
    "titanium",
    "functional group",
    "staining",
    "stabilizer",
    "sucrose",
    "silica gel chromatography",
    "fastener",
    "phosphoric acid",
    "ammonia",
    "boiling",
    "carbonyl group",
    "phosphate buffered saline",
    "Glycerol",
    "Capillaries",
    "hydrolysis reaction",
    "reduced",
    "flash chromatography",
    "placebo",
    "phosphorus",
    "Complementarity Determining Regions",
    "vascular",
    "catalytic",
    "mineral",
    "evaporation",
    "nickel",
    "fluorine",
    "L-glutamic acid",
    "chronic",
    "L-cysteine",
    "upstream manufacturing",
    "heterocycloalkyl group",
    "organic acids",
    "vitamin",
    "magnetic",
    "ELISA",
    "fluoro group",
    "Benzoic acid",
    "mgso4",
    "gelatine",
    "chlorine atom",
    "impurity",
    "alkenes",
    "condensation",
    "Membranes",
    "dimethylformamide",
    "Oryza sativa",
    "haloalkyl group",
    "alcohols",
    "lipase",
    "centrifugation",
    "pellet",
    "cloning",
    "preservative",
    "eluent",
    "Lactose",
    "respiratory gaseous exchange",
    "chloro group",
    "filler",
    "flavoring agent",
    "slurry",
    "secretion",
    "protecting group",
    "aggregation",
    "Phosphotransferases",
    "Bovine Serum Albumin",
    "gelatine desserts",
    "spectral",
    "Gelatin",
    "enhancer",
    "L-leucine",
    "Oryctolagus cuniculus",
    "transfection",
    "semiconductor",
    "potassium hydroxide",
    "reduction reaction",
    "reactant",
    "aluminum",
    "milk",
    "ERVK-25",
    "Head",
    "alteration",
    "transcription factors",
    "side effect",
    "aqueous phase",
    "glass fiber",
    "syrup",
    "chemical reaction product",
    "dissolution",
    "Heparin",
    "Zea mays",
    "propyl group",
    "microbial",
    "abnormal effect",
    "benzyl alcohol",
    "Lysine",
    "Hemoglobins",
    "apoptotic process",
    "sodium acetate",
    "implantation",
    "acyl group",
    "emulsifying agent",
    "ammonium hydroxide",
    "cationic group",
    "fluorine atom",
    "Rattus",
    "(3β)-Cholest-5-en-3-ol",
    "packaging method and process",
    "bending",
    "carbamide",
    "Blood Platelets",
    "elution",
    "labelling",
    "toxic",
    "crystallisation",
    "carboxy methyl cellulose",
    "ablation",
    "sustained",
    "reducing",
    "Polyethylene (PE)",
    "crystallization",
    "pathogens",
    "cream",
    "colorant",
    "mass spectrometry",
    "cytotoxic",
    "pyridyl group",
    "[O-]P([O-])([O-])=O",
    "Breast",
    "chloride anion",
    "waste material",
    "subcutaneous administration",
    "absorbance",
    "lubricant",
    "diffusion process",
    "toxin",
    "Nicotiana tabacum",
    "Sulfuric acid",
    "Leptailurus serval",
    "nucleoside",
    "carboxylic acid derivatives",
    "deficient",
    "Oleic acid",
    "activating",
    "precipitation",
    "Apoptosis",
    "L-glutamine",
    "detergent",
    "Hexapoda",
    "constituent",
    "nicotinic acid",
    "Urinary Bladder",
    "cytotoxicity",
    "Urine",
    "glutamic acid",
    "Vascular Endothelial Growth Factor A",
    "L-tyrosine",
    "dimethyl polysiloxane",
    "bromine atom",
    "glycol",
    "I.V. solution additive Amino Acids",
    "pigment",
    "blood pressure",
    "air",
    "sodium hydride",
    "Stomach",
    "nitric oxide",
    "mass spectrum",
    "pain",
    "restriction endonucleases",
    "Erythrocytes",
    "Glutathione",
    "rna polymer",
    "xanthan gum",
    "component",
    "nicotinamide",
    "Bos taurus",
    "T-Cell Antigen Receptors",
    "glycine",
    "Macrophages",
    "cysteine",
    "calcium carbonate",
    "Hybridomas",
    "Green Fluorescent Proteins",
    "accumulation",
    "acute",
    "gastric",
    "cross linking",
    "coagulation",
    "small molecules",
    "antioxidants",
    "Bacillus subtilis",
    "methanesulfonic acid",
    "B-Lymphocytes",
    "conjugate",
    "L-threonine",
    "Biomass",
    "diet",
    "polyester",
    "Fibrinogen",
    "Oxidoreductases",
    "stress",
    "immune cell",
    "cholesterol",
    "aldehydes",
    "2-Methylpentane",
    "Nucleus",
    "bleeding",
    "polytetrafluoroethylene",
    "retinal",
    "metabolite",
    "Citric acid",
    "Body Fluids",
    "mineral oil",
    "Tetracycline",
    "firing",
    "digestion",
    "Toxin",
    "sorbitol",
    "nutrients",
    "desinfective",
    "Leg",
    "tartaric acid",
    "Alkaline Phosphatase",
    "mammalian cells",
    "Stearic acid",
    "cations",
    "L-serine",
    "endotoxin",
    "Fungi",
    "biopsy",
    "Fibrin",
    "Codon",
    "ketones",
    "toxins",
    "petroleum",
    "western blot",
    "transport",
    "conventional method",
    "n-heptane",
    "nitrogen atoms",
    "phosphorylative",
    "hydrogen chloride",
    "Zea mays subsp mays",
    "lysate",
    "transduction",
    "antigenic",
    "promoting",
    "Leu-Ser",
    "sulfuric acid",
    "Foot",
    "phosphorylation reaction",
    "bromine",
    "anti-microbial",
    "Human Serum Albumin",
    "cyclopropyl group",
    "hormone",
    "ethene",
    "inflammatory",
    "Mannitol",
    "activator",
    "albumin",
    "anti-bacterial",
    "Ethylene",
    "carbamoyl group",
    "Poly (ethylene oxide)",
    "initiatory",
    "nitrogen group",
    "hydrogenation reaction",
    "cyclohexyl group",
    "oxygen atoms",
    "solid phase",
    "Half live",
    "memory",
    "distilled water",
    "Leukocytes",
    "retained",
    "respiratory",
    "nutrition",
    "integrins",
    "acrylic acid",
    "Endothelial Cells",
    "hyaluronan",
    "crystallographic characterization",
    "Arginine",
    "unidentified adenovirus",
    "polyethylene",
    "acetate",
    "microparticle",
    "ceramic",
    "L-phenylalanine",
    "polyvinyl alcohol",
    "incorporation",
    "NMR spectroscopy",
    "D-Mannitol",
    "herbicidal",
    "dialysis",
    "talc",
    "alkyl amino group",
    "byproduct",
    "fragrance",
    "Hair",
    "transmitter",
    "capacitor",
    "urea",
    "Trypsin",
    "phenol",
    "pharmaceutic aid",
    "Gastrointestinal Tract",
    "trypsin",
    "wax",
    "Spleen",
    "protease",
    "polycarbonate",
    "folic acid",
    "Antibiotics FOR TREATMENT OF HEMORRHOIDS AND ANAL FISSURES FOR TOPICAL USE",
    "Antibiotic throat preparations",
    "Uracil",
    "microsphere",
    "Bone Marrow",
    "Ser-Ser",
    "oxidative",
    "Nicotine",
    "calculation method",
    "alkoxycarbonyl group",
    "C2-C6 alkenyl group",
    "NUC1",
    "flavors",
    "Sodium laurylsulphate",
    "Hepacivirus C",
    "nucA",
    "adult",
    "wafers",
    "phospholipids",
    "syndrome",
    "penetration",
    "fumaric acid",
    "(C3-C6) cycloalkyl group",
    "polyoxyethylene sorbitan monooleate",
    "Intron",
    "Aptamer",
    "antioxidant",
    "ammonium acetate",
    "D-glucitol",
    "cell proliferation",
    "Ser-Gly",
    "fuel",
    "anchoring",
    "Lipase",
    "oxalic acid",
    "IFNG",
    "Cell Membrane",
    "lecithin",
    "metabolic process",
    "pectin",
    "irrigation",
    "Cyclodextrin",
    "potentiating",
    "quenching",
    "in-situ storage",
    "polyol",
    "D-Glucitol",
    "L-asparagine",
    "Ser-Leu",
    "RBC",
    "reducing agent",
    "Arteries",
    "triacylglycerols",
    "stainless steel",
    "propionic acid",
    "(C1-C6) alkoxy group",
    "alkyl thio group",
    "substituted aryl group",
    "obesity",
    "1H NMR spectroscopy",
    "Val-Ser",
    "flow cytometry",
    "powder X-ray diffraction",
    "monocyclic group",
    "Chitosan",
    "upper leg",
    "Polypropylene",
    "L-aspartic acid",
    "substituted alkyl group",
    "hydroxypropyl cellulose",
    "aryl aryl group",
    "Central Nervous System",
    "polyacrylic acid",
    "regeneration method",
    "glycyl-threonine",
    "polypropylene",
    "Mouth",
    "metabolism",
    "methylcellulose",
    "permeability",
    "cell growth",
    "methane",
    "L-valine",
    "thin film",
    "Brain",
    "regeneration",
    "real-time PCR",
    "decomposition reaction",
    "Acetic Acid",
    "oligosaccharides",
    "electric field",
    "transplantation",
    "inflammatory disease",
    "Valyl-Threonine",
    "hyaluronic acid",
    "biological regulation",
    "cobalt",
    "intestinal",
    "Keratins",
    "alanine",
    "thiol group",
    "castor oil",
    "bioactive",
    "metals",
    "EGF",
    "fluorescent dye",
    "zeolite",
    "pathological",
    "biocompatible material",
    "pharmacologic effect",
    "potassium chloride",
    "sugars",
    "Formic acid",
    "radioactive",
    "leucyl-lysine",
    "assembly",
    "L-histidine",
    "L-lysine",
    "contamination",
    "alkali",
    "anatomy",
    "Fructose",
    "seryl-proline",
    "proliferating",
    "taxol",
    "green fluorescent protein",
    "polyols",
    "metabolic",
    "Immune System",
    "lysing",
    "Interleukin-8",
    "chromium",
    "polyethylene terephthalate",
    "robotic",
    "angiogenesis",
    "free base",
    "glycosylation reaction",
    "Vitamin C",
    "ENZYMES FOR TREATMENT OF WOUNDS AND ULCERS",
    "Tris",
    "carbon monoxide",
    "preparative HPLC",
    "liquid crystal related substance",
    "deionised water",
    "naphthyl group",
    "butyl group",
    "anti-tumor",
    "acetic anhydride",
    "Leu-Glu",
    "static",
    "Virus Disease",
    "vitamins",
    "liquid phase",
    "herbicide",
    "poly(dimethylsiloxane)",
    "Ligases",
    "Extremities",
    "manganese",
    "threonyl-glycine",
    "acrylate",
    "glycosylation",
    "electrolyte",
    "Antifibrinolytic amino acids",
    "Tris buffer",
    "installation",
    "body fluid",
    "Hip",
    "L-alanine",
    "oxane",
    "Dexamethasone",
    "Crystalline Lens",
    "recombination",
    "oligosaccharide",
    "core material",
    "Trehalose",
    "Hypertension",
    "soil",
    "sodium dodecyl sulfate polyacrylamide gel electrophoresis",
    "L-Methionine",
    "steel",
    "acceleration",
    "anions",
    "Succinic acid",
    "pumping",
    "biodegradation reaction",
    "radiotherapy",
    "Luciferase",
    "Glucose",
    "agar",
    "denaturation",
    "Luciferase family",
    "isobutyl group",
    "hydrocarbyl group",
    "pill",
    "nitrogen atmosphere",
    "immune effect",
    "probiotic",
    "C2-C6 alkynyl group",
    "spraying",
    "Protein Isoforms",
    "cycloalkenyl group",
    "Cartilage",
    "Propionic acid",
    "stabilizing",
    "ventricular",
    "methylene group",
    "edta",
    "L-isoleucine",
    "anti-oxidant",
    "catalytic activity",
    "heparin",
    "quantification",
    "propane",
    "freeze drying",
    "titan oxide",
    "(C1-C3) alkyl group",
    "cereals",
    "conjugation",
    "chelating agent",
    "calcium phosphate",
    "Gly-Ser",
    "reaction time",
    "physical effect",
    "ointment",
    "moulding",
    "buffer solution",
    "Cytosine",
    "morpholine",
    "Peroxidases",
    "leucylproline",
    "Cotton",
    "valyllysine",
    "sulfate",
    "cytotoxic agent",
    "fetal bovine serum",
    "types of analysis",
    "L-methionine",
    "valine",
    "computed tomography",
    "edible fruits",
    "malic acid",
    "Solanum tuberosum",
    "GCG",
    "gravity",
    "lysine",
    "acetyl group",
    "sweetening agent",
    "ADRIAMYCIN",
    "formamide",
    "recrystallisation",
    "aryloxy group",
    "interceptive",
    "adenosine",
    "cutting process",
    "migration",
    "Polysorbate 20",
    "sulfonyl group",
    "fats",
    "stabilization",
    "electrospray ionisation mass spectrometry",
    "thickening agent",
    "vitamin E",
    "Dulbecco’s modiﬁed Eagle's medium",
    "2-amino-2-(hydroxymethyl)propane-1",
    "fungal",
    "Leu-Thr",
    "welding",
    "biphenyl",
    "lotion",
    "n-propyl group",
    "beverage",
    "Polystyrene",
    "anionic group",
    "healing",
    "active pharmaceutical agent",
    "heteroalkyl group",
    "o-xylene",
    "organic compounds",
    "polyoxyethylene sorbitan monolaurate" "bacterial pathogens",
    "Ala-Thr",
    "cytolysis",
    "sulfur atoms",
    "cytosolic",
    "dose–response relationship",
    "Glutamic Acid",
    "aging",
    "Cornea",
    "2-[6-[4",
    "contaminant",
    "infectious",
    "polystyrene",
    "RF1",
    "dispersing agent",
    "immunity",
    "hydroxyalkyl group",
    "animal model",
    "alloy",
    "Tricalcium phosphate",
    "clearance",
    "Clearance",
    "n-butanol",
    "thienyl group",
    "POLB",
    "sodium salts",
    "Vitamin E",
    "nonwoven fabric",
    "bicyclic group",
    "contrast media",
    "Val-Glu",
    "halides",
    "carrageenan",
    "absorbing agent",
    "Peripheral blood mononuclear cell",
    "DPOM",
    "food sweetener",
    "conditioning",
    "thin layer chromatography",
    "alanylproline",
    "microarray",
    "ventilation",
    "Amylases",
    "conjugation with cellular fusion",
    "Doxorubicin",
    "computer program",
    "Ethyl cellulose",
    "prophylaxis",
    "dimer",
    "Ala-Ser",
    "nucleoside derivatives",
    "health",
    "germ cell",
    "imidazole",
    "delayed",
    "phenylalanylserine",
    "Threonine",
    "Gly-Thr",
    "Extracellular Matrix",
    "Hordeum vulgare",
    "Joints",
    "methylidene group",
    "Colon",
    "Dextran",
    "antigen binding proteins",
    "vinyl group",
    "correlated",
    "Microcrystalline cellulose",
    "carbamate",
    "reversed phase HPLC",
    "ammonium",
    "pharmacokinetic",
    "ethyl cellulose",
    "Adenine",
    "Ile-Ser",
    "Leu-Lys",
    "penetrating",
    "granulation",
    "polyvinyl chloride",
    "suppository",
    "hydrazine",
    "cyclopentyl group",
    "cysteine group",
    "wheat",
    "alpha-Amylases",
    "CD3OD",
    "periodic",
    "olive oil",
    "ethers",
    "overexpression",
    "rhodium",
    "optimization",
    "Urea",
    "glutamylalanine",
    "harvesting",
    "swelling",
    "xylene",
    "viral reproduction",
    "microcapsule",
    "(C3-C8) cycloalkyl group",
    "soft tissue",
    "Polyimide",
    "Thr-Leu",
    "Mus sp.",
    "Palmitic acid",
    "(C1-C4)alkoxy group",
    "partition",
    "Capra",
    "Jaw",
    "glycylleucine",
    "Endonucleases",
    "cross linking reagent",
    "Polyvinyl alcohol",
    "Neutrophils",
    "food intake",
    "perfume",
    "wetting agent",
    "prolonged",
    "Retina",
    "fraction",
    "Veins",
    "initiator",
    "Fibronectins",
    "corrosion",
    "exhibiting",
    "proteolythic",
    "calcium chloride",
    "2-propanol",
    "Gallus gallus",
    "mineralic acids",
    "lysylglycine",
    "transient",
    "Mus musculus",
    "suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I",
    "Salicylic acid",
    "Knee",
    "hydrogen bromide",
    "pyrimidinyl group",
    "TNF",
    "phosphate buffer",
    "L-methotrexate",
    "adsorbent",
    "polysorbate 80",
    "eukaryotic cell",
    "Wound",
    "storage",
    "Growth Hormone",
    "vegetable and seed oil",
    "chromosomal",
    "alkylation reaction",
    "Leu-Gly",
    "aspartylglycine",
    "deprotection reaction",
    "thiols",
    "Leu-Pro",
    "Val-Lys",
    "glutamyl-glutamic acid",
    "sodium methoxide",
    "Carboxymethyl cellulose",
    "n-butyl group",
    "pulmonary",
    "chest",
    "methotrexate",
    "Capsid Proteins",
    "Carbonate dianion",
    "subcutaneous injection",
    "elimination reaction",
    "alkali metals",
    "tumor growth",
    "Fingers",
    "ethylene glycol",
    "vaccination",
    "weighing",
    "glycylvaline",
    "Leptin",
    "epithelial cells",
    "formyl group",
    "parenteral administration",
    "biodegradable polymer",
    "L-alanyl-L-glutamic acid",
    "aspartyllysine",
    "L-proline",
    "Hydroxyethyl cellulose",
    "ERVK-6",
    "Phenylalanine",
    "colorless oil",
    "synergetic",
    "VP1",
    "lysylvaline",
    "localization",
    "alkyl aryl group",
    "unidirectional conjugation",
    "mating",
    "Amplicon",
    "annealing",
    "Phe-Ser",
    "Xylose",
    "Imidazole",
    "neutralization reaction",
    "Ser-Val",
    "adverse",
    "selenium",
    "extrusion",
    "electromagnetic radiation",
    "vitamin C",
    "Streptavidin",
    "Thrombin",
    "prolyl-serine",
    "glycyllysine",
    "viability",
    "propylene group",
    "molecular sieve",
    "nonionic surfactant",
    "behavior",
    "inoculation",
    "aspartylglutamate",
    "thrombin",
    "Bioavailability",
    "bioavailability",
    "(C1-C6) haloalkyl group",
    "Rodentia",
    "Carrier Proteins",
    "glutaminyl-glycine",
    "Lipoproteins",
    "HATU",
    "Gly-Leu",
    "Cyclosporine",
    "plasticizer",
    "metal oxides",
    "Vitamin D",
    "freezing",
    "Serinyl-Threonine",
    "combination therapy",
    "benzoic acid",
    "peripheral blood",
    "polyamide",
    "ribozyme",
    "ethoxy group",
    "charge neutralization",
    "deuterium",
    "magnesium chloride",
    "hydroxy functional group",
    "Polyamide",
    "methyl cellulose",
    "Mesotartaric acid",
    "Leucyl-Glutamine",
    "lithium",
    "embryonic structures",
    "furyl group",
    "Zea mays subsp huehuetenangensis",
    "imidazolyl group",
    "Pro-Ser",
    "Calcium",
    "Other lymphomas",
    "(2S)-6-amino-2-[[(2S)-2-aminopropanoyl]amino]hexanoic acid",
    "allergen",
    "unidentified influenza virus",
    "sterols",
    "2qpq",
    "maize",
    "sodium alginate",
    "attenuated",
    "Pancreas",
    "water by type",
    "inactivation",
    "hemA",
    "calcium phosphates",
    "Nylon",
    "alanylglycine",
    "EC 2.7.7.49",
    "Segment-4",
    "cell suspension",
    "Ovis",
    "tungsten",
    "(C1-C8) alkyl group",
    "MeOtBu",
    "Glucagon",
    "block copolymer",
    "corn",
    "sodium laurylsulphate",
    "Heart Valves",
    "atrial",
    "flavonoids",
    "Transfer RNA",
    "N-glycylalanine",
    "insecticidal",
    "soybean oil",
    "fat",
    "spores",
    "Etoposide",
    "trisodium citrate",
    "aliphatic alkanes",
    "aromatic hydrocarbons",
    "temporal effect",
    "suspending agent",
    "piperidine",
    "purified water",
    "Dextrin",
    "Lymph Nodes",
    "Double-Stranded RNA",
    "stock solution",
    "Xylitol",
    "xylitol",
    "Palladium on carbon",
    "Octadecanoic acid",
    "toll-like receptors",
    "hawthorn",
    "bromo group",
    "mixed solution",
    "Aluminium silicate",
    "Fibroblast Growth Factor 2",
    "paraffin wax",
    "Heart Ventricles",
    "docosahexaenoic acid",
    "Aspartic Acid",
    "poly(lactic acid) polymer",
    "Ammonium chloride",
    "ginseng",
    "carboxylic acids",
    "atmosphere",
    "alkyl sulfonyl group",
    "triphosphate",
    "Sirolimus",
    "retroviral",
    "Adipose Tissue",
    "polycaprolactone",
    "thiophosphate",
    "Triticum aestivum",
    "favourable",
    "1-Ethyl-3-(3-dimethylaminopropyl)carbodiimide",
    "molybdenum",
    "heteroarylalkyl group",
    "reverse transcription PCR",
    "intraperitoneal administration",
    "N-Vinylpyrrolidone",
    "modifier",
    "sec-butyl group",
    "Hepatocytes",
    "stearic acid",
    "HEPES buffer",
    "ice water",
    "(C1-C10) alkyl group",
    "respiration",
    "osmotic",
    "Hepatitis B virus",
    "nucleoside group",
    "terpenes",
    "propellant",
    "adverse effect",
    "Threoninyl-Valine",
    "propanol",
    "Bacillus <bacterium>",
    "winding",
    "Calcium Carbonate",
    "lithium hydroxide",
    "Ala-Pro",
    "guar gum",
    "hemagglutinin",
    "cyclobutyl group",
    "Phenol",
    "dysfunction",
    "sirolimus",
    "Vinblastine",
    "α-tocopherol",
    "micelle",
    "nitriles",
    "ISOLEUCINE",
    "competitive",
    "dehydration reaction",
    "textile",
    "piperidinyl group",
    "molecular cloning",
    "L-prolylglycine",
    "thermosoftening plastic",
    "VITAMINS",
    "secreting",
    "Vitamin IV solution additives",
    "cyclohexane",
    "Cercopithecidae",
    "Saliva",
    "D-tryptophane",
    "aspartic acid",
    "Collagenase family",
    "biosynthesis",
    "haemopoietic",
    "fatty alcohols",
    "n-methylpyrrolidone",
    "DMA",
    "vegetables",
    "sodium borohydride",
    "alkoxy alkyl group",
    "unidentified retrovirus",
    "vegetable oil",
    "Ion Channels",
    "Glu-Leu",
    "beta-Galactosidase",
    "Phe-Thr",
    "val-gly",
    "phenoxy group",
    "sesame oil",
    "haloalkoxy group",
    "wound healing",
    "facial",
    "prolylglutamic acid",
    "retinol",
    "Intestines",
    "Neuraminidase",
    "Riboflavin",
    "pyrazolyl group",
    "Sense strand",
    "Muramidase",
    "Gly-Lys",
    "nicotine",
    "Tragacanth",
    "plasma concentration",
    "combustion reaction",
    "reinforcing",
    "Hydrolases",
    "Phospholipids",
    "cardiovascular",
    "sorbic acid",
    "Microtubules",
    "sensory",
    "2-propenyl group",
    "luminiscence type",
    "dextrose",
    "rolling process",
    "acacia gum",
    "protein binding assay",
    "Hydroxypropyl cellulose",
    "lysyllysine",
    "esterification reaction",
    "foil",
    "hydrochlorides",
    "Styrene",
    "polyacrylamide",
    "Thromboplastin",
    "thiazolyl group",
    "carboxymethyl-cellulose",
    "Lactobacillus",
    "insulation",
    "Cytomegalovirus",
    "activated carbon",
    "fluorescence intensity",
    "Dementia",
    "weekly",
    "homologous recombination",
    "nitric acid",
    "Asparagine",
    "Lys-Leu",
    "ischemic",
    "Ribonucleases",
    "LDL Lipoproteins",
    "impaired",
    "latex",
    "titanium dioxide",
    "Agarose",
    "breeding",
    "hydrates",
    "Leu-Asn",
    "aspartyl-phenylalanine",
    "Uridine",
    "cycloalkyl alkyl group",
    "anhydrides",
    "reaction media",
    "saponins",
    "cumulative",
    "styrene",
    "Thymine",
    "Matrix Metalloproteinases",
    "Corn starch",
    "hexyl group",
    "Aspartyl-Threonine",
    "test method",
    "exercise",
    "Transferases",
    "lysylproline",
    "Spinal Cord",
    "Ser-Ala",
    "Trisodium citrate",
    "nylon",
    "drilling",
    "unidentified phage",
    "Ubiquitin",
    "Glyphosate",
    "Membrane Proteins",
    "D-serine",
    "triphenylphosphine",
    "Blood Cells",
    "L-ascorbic acid",
    "encapsulation",
    "Chromatin",
    "asparagine",
    "gly-val",
    "lethal",
    "Tendons",
    "Recombinases",
    "final product",
    "Fluorouracil",
    "Pseudomonas aeruginosa",
    "renotropic",
    "ultra-filtration",
    "methyl p-hydroxybenzoate",
    "acrylamide",
    "aspartyl-aspartic acid",
    "Ser-Pro",
    "carbocyclic group",
    "Asp-Lys",
    "polyether",
    "food flavoring agent",
    "dialkyl amino group",
    "ammonium chloride",
    "alginate",
    "pharmacologic agent",
    "butane",
    "inert solvent",
    "tert-butyloxycarbonyl group",
    "transplatin",
    "monochloramine",
    "pyrrolidinyl group",
    "discharging",
    "stenosis",
    "4-dimethylaminopyridine",
    "lactate",
    "irradiating",
    "Leucaena leucocephala",
    "succinic acid",
    "Arg-Ser",
    "zinc oxide",
    "shock",
    "sodium azide",
    "Thr-Ser",
    "sleep",
    "prolylglycine",
    "disintegrant",
    "transition metals",
    "Lecithin",
    "Chemokines",
    "formula milk",
    "dissociation reaction",
    "N-oxides",
    "purge",
    "cDNA synthesis",
    "maturation",
    "Tyrosyl-Serine",
    "effect on skin",
    "acyloxy group",
    "genetic engineering",
    "poloxamer",
    "volatile oil",
    "caffeine",
    "Serine Proteases",
    "arginine glutamate",
    "inert gas",
    "parathyroid hormone",
    "arginine",
    "body temperature",
    "culture supernatant",
    "lignin",
    "dissociations",
    "Exosomes",
    "Thymidine",
    "cd3od",
    "organic bases",
    "aspartyl-proline",
    "Bleomycin",
    "Serinyl-Arginine",
    "Triphenylphosphine",
    "Methylparaben",
    "pro glu",
    "all-trans-retinol",
    "benzylpenicillin",
    "Benzyl alcohol",
    "tetracycline",
    "Cellulase",
    "general method",
    "N-glycylglutamic acid",
    "bromide",
    "prognosis",
    "parasites",
    "Respiratory syncytial virus",
    "piperazinyl group",
    "Val-Pro",
    "cement",
    "gas chromatography",
    "Isoleucyl-Threonine",
    "wood",
    "Convulsion",
    "hypoxic",
    "benzoyl group",
    "Dextromethorphan",
    "α-Glu-Val",
    "Tamoxifen",
    "fungicidal",
    "Horseradish Peroxidase",
    "L-arginine",
    "arginyllysine",
    "Ampicillin",
    "lysylglutamic acid",
    "progesterone",
    "spontaneous",
    "n-butyllithium",
    "weight loss",
    "Transferrin",
    "ethynyl group",
    "titration",
    "Ovary",
    "shaping process",
    "sunscreening agent",
    "amide group",
    "Asp-Ser",
    "phosphoric acid derivatives",
    "polysorbate",
    "immonomodulatory",
    "Bicarbonate",
    "3-pyridyl group",
    "asparaginyl-proline",
    "pharmaceutical agent",
    "ampicillin",
    "nuclear magnetic resonance spectrum",
    "arginylproline",
    "DNA-binding",
    "cell culture media",
    "Bacterial infection",
    "Asp-Glu",
    "affinity chromatography",
    "polyamine",
    "(+)-methoprene",
    "Tissue plasminogen activator",
    "Ala-Leu",
    "P-Toluenesulfonic acid",
    "piperazine",
    "glycylglutamine",
    "Polypropylene glycol",
    "Ala-Gly",
    "Methanesulfonyl chloride",
    "Asp-Gly",
    "electrospray ionisation",
    "glycolic acid",
    "Telomerase",
    "aspartyltyrosine",
    "Stroke",
    "elemental analysis",
    "Epithelium",
    "acrylic acid group",
    "diamond",
    "resting",
    "triggered",
    "Cytoplasm",
    "trifluoromethoxy group",
    "resection",
    "107444-51-9",
    "polyepoxide",
    "corn starch",
    "sodium citrate",
    "pyrazinyl group",
    "Vertebrata <Metazoa>",
    "polyadenylating",
    "etching",
    "aspirin",
    "Val-Gln",
    "Lys-Gly",
    "polyolefin",
    "cisplatin",
    "infiltration",
    "methyl esters",
    "cell cycle",
    "Epidermis",
    "cell killing",
    "nanomaterial",
    "Lys-Ser",
    "synchronised",
    "Lauric acid",
    "peroxides",
    "Primates",
    "Fibrinogen containing hemostatics",
    "probiotics",
    "ciclosporin",
    "Chitin",
    "alanylglutamine",
    "surface plasmon resonance spectroscopy",
    "Caesium carbonate",
    "Glutamine",
    "cell viability",
    "preservation",
    "pyrrolyl group",
    "ammonium salts",
    "flux",
    "keto-D-fructose",
    "statistical method",
    "dyeing",
    "Capsid",
    "Oryza",
    "homopolymer",
    "osteoblast",
    "Nitrocellulose",
    "Cell Wall",
    "shampoo",
    "acetic acid;2",
    "Thr-Thr",
    "glycyl group",
    "arginyl-glutamine",
    "Sepharose",
    "L-lysyl-L-alanine",
    "Cross linker",
    "hydroxybenzotriazole",
    "fibronectin",
    "thionyl chloride",
    "nitrocellulos",
    "unidentified baculovirus",
    "Epoxy",
    "monosaccharides",
    "gly ala",
    "gelatin capsule",
    "Camptothecin",
    "diols",
    "Thr-Gly",
    "Unbound",
    "enteric coating",
    "acceptor",
    "Docetaxel",
    "carboxylates",
    "Gly-Gln",
    "morpholinyl group",
    "oxazolyl group",
    "Lanolin",
    "Glutaminyl-Leucine",
    "recombinant expression",
    "Consensus sequence",
    "Glu-Ala",
    "fluorescent proteins",
    "disulfides",
    "Ligaments",
    "Glycogen",
    "electron beam technology",
    "killing",
    "acetamide",
    "pathogenesis",
    "Ser-Asp",
    "receptor tyrosine kinases",
    "polyamide (building material)",
    "Chloramphenicol",
    "Pro-Ala",
    "Zea",
    "Nicotiana",
    "Drug Delivery Device",
    "warming",
    "Thionyl chloride",
    "small intestine",
    "fine particle",
    "coloring",
    "polyacrylate",
    "Theophylline",
    "magnesium oxide",
    "melt",
    "n-Butyllithium",
    "4-Dimethylaminopyridine",
    "289-95-2",
    "Shoulder",
    "Lys-Val",
    "cerebral",
    "catalytic reaction",
    "soap",
    "zinc monoxide",
    "Actinopterygii",
    "circulation",
    "daily",
    "carbon fibre reinforced carbon",
    "X-ray diffraction",
    "Glu-Lys",
    "D-(+)-Galactose",
    "ion exchange",
    "fractionation",
    "tissue damage",
    "FIBRIN",
    "2-pyridyl group",
    "lectin",
    "alkyl carbonyl group",
    "tragacanth",
    "magnetic particle",
    "maleic acid",
    "Agar",
    "acetylsalicylic acid",
    "thiamine",
    "Aorta",
    "ozone",
    "ring formation reaction",
    "Arachis hypogaea",
    "clinical diagnostic method",
    "fragmentation reaction",
    "vitamin A",
    "ampul",
    "Ser-Asn",
    "Ankle",
    "Tibia",
    "milling",
    "Abdomen",
    "smoke",
    "all-trans-retinaldehyde",
    "ethanolamine",
    "coconut oil",
    "fluorescein",
    "(C1-C4) haloalkyl group",
    "Polyphenylene oxide",
    "sodium phosphate",
    "benzamide",
    "Superoxide Dismutase",
    "Start codon",
    "Fumaric acid",
    "Aves",
    "coolant",
    "Ser-Glu",
    "Skeleton",
    "capsaicin",
    "ammonium sulphate",
    "Val-Asn",
    "2-butanone",
    "mouse model",
    "ink",
    "cacl2",
    "tyrosyltyrosine",
    "Keratinocytes",
    "alkylating agent",
    "Lactoferrin",
    "spectroscopical analysis",
    "streptomycin",
    "Raman spectroscopy",
    "hydration reaction",
    "paraformaldehyde",
    "KDR",
    "hydrolyzing",
    "N-Acetylglucosamine",
    "additional",
    "Ile-Gly",
    "L-arginyl-L-glutamic acid",
    "aqueous suspension",
    "eyesight",
    "trisodium phosphate",
    "dietary supplement",
    "indolyl group",
    "Vancomycin",
    "adherent",
    "immersion",
    "Nails",
    "substituted cycloalkyl group",
    "tetrahydropyrrole",
    "Wnt",
    "alanine group",
    "silicone rubber",
    "Methyl acetate",
    "Sus scrofa",
    "serotonin",
    "cocoa butter",
    "tertiary amines",
    "aromatic heterocyclic group",
    "prolylleucine",
    "meals",
    "mucosa",
    "wrinkles",
    "phenols",
    "reinforcement",
    "poly(methyl methacrylate)",
    "oligonucleotide probe",
    "Aspartame",
    "Thr-Pro",
    "water-soluble polymer",
    "hydrophilic polymer",
    "epoxides",
    "agarose gel",
    "curcumin",
    "Asn-Ser",
    "Lys-Thr",
    "reverse transcription",
    "Tyrosyl-Threonine",
    "mercury",
    "taste",
    "molecular docking",
    "carbocyclyl group",
    "glycylglycine zwitterion",
    "Gln-Gly",
    "electricity",
    "thioethers",
    "Indomethacin",
    "adipic acid",
    "vitamin E derivatives",
    "2-[[(2S)-2-amino-5-(diaminomethylideneamino)pentanoyl]amino]acetic acid",
    "Asparaginyl-Leucine",
    "Saccharomyces carlsbergensis",
    "Thymidine Kinase",
    "Leu-His",
    "physiological saline solution",
    "Ala-Asn",
    "Elastin",
    "lysine group",
    "light adaptation",
    "aberrant",
    "anionic surfactant",
    "Candida albicans",
    "Thr-Ala",
    "investigational therapy",
    "immunohistochemistry",
    "polymethyl methacrylate",
    "phosphatidylcholine",
    "Nose",
    "Oligonucleotide Probes",
    "adaptive",
    "Canis",
    "Pro-Leu",
    "Canis lupus familiaris",
    "Indole",
    "diluting",
    "Three prime untranslated region",
    "sodium starch glycolate",
    "Lower Extremity",
    "Ala-Gln",
    "aniline",
    "Methyl iodide",
    "Heart Atria",
    "L-lactate dehydrogenases",
    "oocyte",
    "Theobroma cacao",
    "vitamin derivatives",
    "synthetic fiber",
    "rubber",
    "Agrobacterium",
    "hydration",
    "(C3-C7) cycloalkyl group",
    "isomerization reaction",
    "Aspartyl-Asparagine",
    "EC 1.14.18.1",
    "dimethoxyethane",
    "Esophagus",
    "Uterus",
    "proton nuclear magnetic resonance spectrum",
    "oral dosage form",
    "pro-inflamatory",
    "mixed solvent",
    "pharmacokinetics",
    "potassium bicarbonate",
    "Inositol",
    "machine learning",
    "propyl p-hydroxybenzoate",
    "ZrO2",
    "EC 6.1.1.-",
    "nebulizer",
    "heterocyclylalkyl group",
    "Kanamycin",
    "Isoleucyl-Lysine",
    "Adipic acid",
    "flushing procedure",
    "ethyl acetate;hexane",
    "Serinyl-Lysine",
    "insulator",
    "Ribavirin",
    "trace mineral",
    "Lactobacillus plantarum",
    "diisopropyl ether",
    "recycling",
    "prolylvaline",
    "fluorescence-activated cell sorting",
    "sodium;boron(1-)",
    "inorganic bases",
    "unsaturated fatty acids",
    "2-mercaptoethanol",
    "methacrylic acid",
    "Peroxidase",
    "Lys-Lys",
    "phosphate group",
    "tomography",
    "Polyglycolide",
    "pesticide",
    "confectionery",
    "oxo group",
    "Glu-Ser",
    "Thea sinensis",
    "dihydrofolate reductase family",
    "drinking water",
    "wash buffer",
    "nucleation",
    "Polyethylenimine",
    "glycylproline",
    "Guanine",
    "whitening",
    "Segment 5",
    "Coronary Vessels",
    "Tacrolimus",
    "t-BuOH",
    "aminoalkyl group",
    "filter cake",
    "Lycopersicon esculentum",
    "pyrrolidine",
    "kanamycin",
    "physiological condition",
    "opioid",
    "Vitamin",
    "hydroxyethyl cellulose",
    "boron",
    "EC 1.11.1.6",
    "sample solution",
    "(E)-but-2-enedioate;hydron",
    "4-fluorophenyl group",
    "Myristic acid",
    "printing",
    "HF",
    "beta Catenin",
    "tyrosyl-lysine",
    "histidylleucine",
    "Viral Proteins",
    "cracking",
    "Guanosine",
    "Calcitonin",
    "rhythmic process",
    "pentyl group",
    "corn oil",
    "polyphenols",
    "epoxy group",
    "Vitis vinifera",
    "astaxanthin",
    "absorption spectrum",
    "Ammonium sulfate",
    "Arg-Gln",
    "Mitoxantrone",
    "potassium acetate",
    "phage display",
    "Nipples",
    "sensitizing",
    "morphologic",
    "regenerating",
    "gluconic acid",
    "indole",
    "plating",
    "Polysorbate 80",
    "Gly-Arg",
    "photoresistant polymer",
    "Homo",
    "liquid chromatography",
    "Butanol",
    "CHCl3",
    "Gly-Glu",
    "Lys-Pro",
    "Glioblastoma",
    "differential scanning calorimetry",
    "volatile agent",
    "ionic liquid",
    "endothelial",
    "pentane",
    "Maltodextrin",
    "2-((2",
    "Erlotinib",
    "calcium cation",
    "Somatostatin",
    "positron emission tomography",
    "Exendin-4",
    "Pupil",
    "urinary",
    "dust",
    "Saccharin",
    "alkenylene group",
    "C6-C10 aryl group",
    "Maltose",
    "Erythritol",
    "Glycosaminoglycan",
    "conditioned culture media",
    "Glu-Glu",
    "sunscreen",
    "quartz",
    "polar solvent",
    "pyrimidines",
    "2-[(2-amino-3-methylpentanoyl)amino]pentanedioic acid",
    "inducer",
    "bifunctional",
    "Thr-Phe",
    "knee joint",
    "polylactic acid",
    "fungicide",
    "rock",
    "Panax quinquefolius",
    "coumarin",
    "Exon",
    "Threoninyl-Lysine",
    "Modified starch",
    "quality control method",
    "DEOXYTHYMIDINE",
    "abdominal",
    "primary amines",
    "toxicity",
    "drugs",
    "hydrogen",
    "method",
    "machining",
    "methods",
    "effects",
    "drug administration",
    "pulverizing process",
    "quantitative analysis",
    "carbon",
    "solvent",
    "sodium chloride",
    "cells",
    "disease",
    "method",
    "degradation reaction",
    "calcium salts",
    "potassium salts",
    "lactones",
    "kidney",
    "brain",
    "liver",
    "heart",
    "starch",
    "flushing",
    "therapeutic",
    "spinning",
    "drug development",
    "drug design",
    "rare earth metals",
    "assay method",
    "sodium",
    "potassium",
    "calcium",
    "magnesium",
    "manganese",
    "iron",
    "ascorbate",
    "progression",  # disease progress in
    "grinding",
    "buffering",
    "lubricating",
    "injurious",
    "oxygen atom",
    "atom",
    "dietary",
    "somatic",
    "somatic cell",
    "modified proteins",
    "guar gum",
    "maltitol",
    "masking",
    "wellbeing",
    "kidney cell",
    "inflammatory process",
    "hydrogen",
    "antitubercular antibiotics",
    "ophthalmologic antibiotics",
    "intestinal antibiotics",
    "gynecological antibiotics",
    "topical antifungal antibiotics",
    "potato starch",
    "royal jelly",
    "diagnostic procedure",
    "mental",
    "physiological processes and functions",
    "pattern recognition",
    "sorbic acid",
    "soaking",
    "dimensional analysis",
    "cluster analysis",
    "effect on protein",
    "regression analysis",
    "natural polymer",
    "synthetic polymer",
    "pharmacodynamic",
    "pharmacogenomic",
    "animal cell",
    "drug screening",
    "mixing",
    "bile salts",
    "cell based assay",
    "muscle cells",
    "cell function",
    "water",
    "aminals",
    "sodium",
    "seasonal",
    "behavioural",
    "mental health",
    "biological processes and functions",
)
