LARGE_PHARMA_KEYWORDS = [
    "ABBVIE",  # ABBVIE INC
    "AMGEN",  # AMGEN INC
    "ASTRAZENECA",  # ASTRAZENECA AB
    "BAYER",  # BAYER AG, Bayer Pharma AG
    "BOEHRINGER INGELHEIM",  # BOEHRINGER INGELHEIM INT, BOEHRINGER INGELHEIM PHARMA
    "BRISTOL MYERS SQUIBB",  # BRISTOL MYERS SQUIBB CO
    "ELI LILLY",  # LILLY CO ELI
    "LILLY",
    "GENENTECH",  # GENENTECH INC
    "GILEAD",  # GILEAD SCIENCES INC
    "GLAXO",  # GLAXO GROUP LTD
    "GLAXOSMITHKLINE",  # GLAXOSMITHKLINE IP DEV LTD
    "GSK",
    "JANSSEN",  # JANSSEN PHARMACEUTICA NV
    "MERCK",  # MERCK SHARP & DOHME
    "MITSUBISHI",  # MITSUBISHI TANABE PHARMA CORP
    "NOVARTIS",  # NOVARTIS AG
    "NOVO NORDISK",
    "PFIZER",
    "REGENERON",  # REGENERON PHARMACEUTICALS
    "ROCHE",  # HOFFMANN LA ROCHE
    "TAKEDA",  # TAKEDA PHARMACEUTICAL
]
