LARGE_PHARMA_KEYWORDS = [
    "Abbott",
    "ABBVIE",  # ABBVIE INC
    "AMGEN",  # AMGEN INC
    "Allergan",
    "ASTRAZENECA",  # ASTRAZENECA AB
    "BAYER",  # BAYER AG, Bayer Pharma AG
    "BIOGEN",  # BIOGEN IDEC INC
    "BOEHRINGER INGELHEIM",  # BOEHRINGER INGELHEIM INT, BOEHRINGER INGELHEIM PHARMA
    "BRISTOL[ -]?MYERS SQUIBB",  # BRISTOL MYERS SQUIBB CO
    "ELI LILLY",  # LILLY CO ELI
    "LILLY",
    "GENENTECH",  # GENENTECH INC
    "GILEAD",  # GILEAD SCIENCES INC
    "GLAXO",  # GLAXO GROUP LTD
    "GLAXOSMITHKLINE",  # GLAXOSMITHKLINE IP DEV LTD
    "GSK",
    "JANSSEN",  # JANSSEN PHARMACEUTICA NV
    "MERCK",  # MERCK SHARP & DOHME
    "MITSUBISHI",  # MITSUBISHI TANABE PHARMA CORP
    "NOVARTIS",  # NOVARTIS AG
    "NOVO NORDISK",
    "PFIZER",
    "REGENERON",  # REGENERON PHARMACEUTICALS
    "ROCHE",  # HOFFMANN LA ROCHE
    "sanofi",  # SANOFI AVENTIS DEUTSCHLAND
    "TAKEDA",  # TAKEDA PHARMACEUTICAL
]

COMPANY_STRINGS = [
    "grp",
    "HLDGS?",
    "HOLDINGS",
    "international",
    "intl",
    "IP",
    "INTELLECTUAL PROPERTY",
    r"I\.?N\.?C\.?",
    r"I\.?N\.?D\.?",
    "INDUSTRY",
    "INDUSTRIES",
    "INVEST(?:MENTS)?",
    "PATENTS?",
    r"b\.?v\.?",
    r"L\.?T\.?D\.?",
    r"I\.?N\.?C\.?",
    "CORP(?:ORATION)?",
    "COMPANY",
    "consumer[ ]?care",
    r"C\.?O\.?",
    r"D\.?B\.?A",
    r"L\.?L\.?C",
    "LIMITED",
    r"P\.?L\.?C",
    r"L\.?P\.?",
    r"L\.?L\.?P\.?",
    "GMBH",
    "AB",
    "AG",
    "AGENCY",
    "APS",
    "A[/]?S",
    "ASSETS",
    "ASD",
    "AVG",
    "(?<!for |of |and )BIOLOGY?",
    "(?<!for |of |and )BIOL(?:OGICALS?)?",
    "(?<!for |of |and )BIOSCI(?:ENCES?)?",
    "(?<!for |of |and )BIOSCIENCES?",
    "BIOTECH?(?:NOLOGY)?",
    "BUS",
    "BV",
    "CA",
    "CHEM(?:ICAL)?(?:S)?",
    "COMMONWEALTH",
    "COOP",
    "CONSUMER",
    "CROPSCIENCE",
    "DEV(?:ELOPMENT)?",
    "DIAGNOSTICS?",
    "EDU(?:CATION)?",
    "ELECTRONICS?",
    "ENG",
    "ENTERP(?:RISE)?S?",
    "europharm",
    "FARM",
    "FARMA",
    "FOUND(?:ATION)?",
    "GROUP",
    "GLOBAL",
    "H",
    "(?<!for |of |and )HEALTH(?:CARE)?",
    "HEALT",
    "HIGH TECH",
    "HIGHER",
    "IDEC",
    "INT",
    "KG",
    r"k\.?k\.?",
    "LICENSING",
    "LTS",
    "LIFE[ ]?SCIENCES?",
    "MANI(?:UFACTURING)?",
    "MFG",
    "Manufacturing",
    "MATERIAL[ ]?SCIENCE",
    "MED(?:ICAL)?(?: college)?(?: of)?",
    "molecular",
    "NETWORK",
    "No {0-9}",  # No 2
    "NV",
    "OPERATIONS?",
    "PARTICIPATIONS?",
    "PARTNERSHIPS?",
    "PETROCHEMICALS?",
    "(?bio[ -]?)?PHARMA?S?",
    "(?bio[ -]?)?PHARMACEUTICAL?S?",
    "PHARAMACEUTICAL?S?",
    "PLANT",
    "PLC",
    "Plastics",
    "PRIVATE",
    "PROD",
    "PRODUCTS?",
    "PTE",
    "PTY",
    "(?<!for |of )R and D",
    "(?<!for |of )R&Db?",
    "RES",
    "(?<!for |of )RES & (?:TECH|DEV)",
    "(?<!for |of )RESEARCH(?: (?:&|and) DEV(?:ELOPMENT)?)?",
    "SA",
    "SCI",
    "SCIENT",
    "(?<!for |of |and )sciences?",
    "SCIENTIFIC",
    "SE",
    "SERV(?:ICES?)?",
    "SPA",
    "SYNTHELABO",
    "SYS",
    "SYST(?:EM)?S?",
    "TECH",
    "(?<!of |and )TECHNOLOG(?:Y|IES)?",
    "TECHNOLOGY SERVICES?",
    "THERAPEUTICS?",
    "therap(?:eutics|ie)s?",
]
