- text: Method of treating ulcerative colitis with anti-il-12/il23 antibody
  entities:
    moas:
      - anti-il-12/il23 antibody
    diseases:
      - ulcerative colitis
- text: Making (2h-1,2,3-triazol-2-yl)phenyl compounds as orexin receptor modulators
  entities:
    classes:
      - (2h-1,2,3-triazol-2-yl)phenyl compounds
    moas:
      - orexin receptor modulator
- text: Antibodies that neutralize coagulase activity during staphylococcus aureus disease
  entities:
    moas:
      - coagulase-neutralizing antibodies
    diseases:
      - staphylococcus aureus
- text: treating multiple myeloma with carfilzomib, dexamethasone, and an antibody that recognizes cd38
  entities:
    compounds:
      - carfilzomib
      - dexamethasone
    moas:
      - cd38 antibody
    diseases:
      - multiple myeloma
- text: Cross-reactive epitope for multiple sclerosis
  entities:
    moas:
      - Cross-reactive epitope
    diseases:
      - multiple sclerosis
- text: Chimeric antigen receptors targeting cd-19
  entities:
    moas:
      - cd-19 chimeric antigen receptors
- text: ANTIBODY TARGETING CELL SURFACE DEPOSITED COMPLEMENT PROTEIN C3d
  entities:
    moas:
      - C3d Complement Protein Antibody
- text: Anti-h7n9 fully-human monoclonal antibody 5j13; application therefor
  entities:
    moas:
      - Anti-h7n9 fully-human monoclonal antibody 5j13
- text: Indazole and azaindazole btk inhibitors
  entities:
    moas:
      - btk inhibitor
    compounds:
      - indazole
      - azaindazoles
- text: Peptides inhibiting cold-inducible rna binding protein activity
  entities:
    moas:
      - cold-inducible rna binding protein inhibitor
    classes:
      - peptide
- text: COMPOSITIONS FOR MODULATION OF MONOCYTOPOISIS
  entities:
    moas:
      - monocytopoiesis modulator
- text: Covalent inhibitors of pad4
  entities:
    moas:
      - covalent pad4 inhibitor
- text: Tachykinin inhibitors which act at the NK1 and NK2 receptors
  entities:
    moas:
      - tachykinin inhibitor
      - NK1 receptor antagonist
      - NK2 receptor antagonist
- text: Compound inhibits ice activity and may be agents against il-1-, apoptosis-, and ifn-y-mediated diseases
  entities:
    moas:
      - ice inhibitor
    diseases:
      - il-1-mediated diseases
      - apoptosis-mediated diseases
      - ifn-y-mediated diseases
- text: Inhibitors to elevate certain plasma lipid levels, including HDL-cholesterol
  entities:
    moas:
      - lipid level modulator
      - HDL-cholesterol level modulator
