- text: Safe and effective method of treating ulcerative colitis with anti-il-12/il23 antibody
  entities:
    MECHANISM:
      - anti-il-12/il23 antibody
    DISEASE:
      - ulcerative colitis
- text: Improved synthetic methods of making (2h-1,2,3-triazol-2-yl)phenyl compounds as orexin receptor modulators
  entities:
    CLASS:
      - (2h-1,2,3-triazol-2-yl)phenyl compounds
    MECHANISM:
      - orexin receptor modulator
- text: Compositions and methods related to antibodies that neutralize coagulase activity during staphylococcus aureus disease
  entities:
    MECHANISM:
      - coagulase-neutralizing antibodies
    DISEASE:
      - staphylococcus aureus
- text: Methods of treating multiple myeloma with a triplet therapy of carfilzomib, dexamethasone, and an antibody that specifically recognizes cd38.
  entities:
    COMPOUND:
      - carfilzomib
      - dexamethasone
    MECHANISM:
      - cd38 antibody
    DISEASE:
      - multiple myeloma
- text: GBA1 Gene Therapy (PR001)  Parkinson's disease  Phase II Phase II trial is ongoing.
  entities:
    MECHANISM:
      - GBA1 Gene Therapy
    COMPOUND:
      - PR001
    DISEASE:
      - Parkinson's disease
- text: Cross-reactive epitope for multiple sclerosis
  entities:
    MECHANISM:
      - Cross-reactive epitope
    DISEASE:
      - multiple sclerosis
- text: Cross-reactive epitope for multiple sclerosis
  entities:
    MECHANISM:
      - Cross-reactive epitope
    DISEASE:
      - multiple sclerosis
- text: Chimeric antigen receptors targeting cd-19
  entities:
    MECHANISM:
      - cd-19 chimeric antigen receptors
- text: ANTIBODY TARGETING CELL SURFACE DEPOSITED COMPLEMENT PROTEIN C3d AND USE THEREOF
  entities:
    MECHANISM:
      - C3d Complement Protein Antibody
- text: Tumor necrosis factor (tnf) superfamily receptor binding molecules and uses thereof
  entities:
    MECHANISM:
      - TNF receptor binding molecules
- text: Anti-h7n9 fully-human monoclonal antibody 5j13, preparation method therefor, and application thereof
  entities:
    MECHANISM:
      - Anti-h7n9 fully-human monoclonal antibody 5j13
- text: Indazole and azaindazole btk inhibitors
  entities:
    MECHANISM:
      - btk inhibitor
    COMPOUND:
      - indazole
      - azaindazole
- text: Antibodies targeting human claudin 18.2 and uses thereof
  entities:
    MECHANISM:
      - anti-claudin 18.2 antibody
